using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>
///     Generates a zero-allocation <c>EscapeCodes</c> static class from enums
///     annotated with <c>[TerminalEscape]</c>.
/// </summary>
/// <remarks>
///     <para>
///         The generated class holds precomputed ECMA-48 sequences as
///         <see cref="ReadOnlySpan{T}" /> literals (stack-only, no runtime
///         allocation) plus stackalloc-based CSI/SGR formatters for
///         parameterized sequences — replacing hand-written
///         <c>"\x1b[...m"</c> string literals in renderer backends.
///     </para>
///     <para>
///         Three canonical vocabularies (fixed ECMA-48/DEC standard, keyed by
///         enum name) extend the generated API:
///         <list type="bullet">
///             <item><c>Color8Bit</c> — SGR 30–37 / 90–97 palette spans; value 0 maps to the reset-to-default codes (39/49).</item>
///             <item><c>CursorDirection</c> — CSI n A/B/C/D movement + CUP positioning formatters.</item>
///             <item><c>StyleFlag</c> — SGR decoration params (Bold=1, Dim=2, Italic=3, Underline=4, Strike=9, Reverse=7).</item>
///         </list>
///         Enums annotated but not matching a canonical vocabulary still
///         trigger generation of the shared control-sequence section.
///     </para>
/// </remarks>
[Generator]
public sealed class EscapeCodeGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Harbor.CodeGen.TerminalEscapeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enums = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is EnumDeclarationSyntax,
            static (ctx, _) => EscapeEnumInfo.Create((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(enums.Collect(), static (spc, list) => Emit(spc, list));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<EscapeEnumInfo> enums)
    {
        if (enums.IsEmpty)
        {
            return;
        }

        foreach (var group in enums.GroupBy(static e => e.Namespace).Where(static g => g.All(static e => e.Members.Length > 0)))
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Harbor.CodeGen.EscapeCodeGenerator from [TerminalEscape] enums.");
            sb.AppendLine("// Zero-allocation ECMA-48 tables — do not edit; hand-written literals belong in EscapeCodeStrategy.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            string ns = group.Key;
            if (ns.Length > 0)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine("/// <summary>Generated ECMA-48 escape-code tables (source: [TerminalEscape] enums).</summary>");
            sb.AppendLine("public static class EscapeCodes");
            sb.AppendLine("{");

            EmitControlSequences(sb);

            var color = group.FirstOrDefault(static e => e.Name == "Color8Bit");
            if (color is not null)
            {
                EmitColorApi(sb, color);
            }

            var cursor = group.FirstOrDefault(static e => e.Name == "CursorDirection");
            if (cursor is not null)
            {
                EmitCursorApi(sb);
            }

            var style = group.FirstOrDefault(static e => e.Name == "StyleFlag");
            if (style is not null)
            {
                EmitStyleApi(sb, style);
            }

            sb.AppendLine("}");

            string fileName = ns.Length == 0 ? "EscapeCodes.g.cs" : $"EscapeCodes_{Sanitize(ns)}.g.cs";
            spc.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void EmitControlSequences(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>SGR reset — all attributes off.</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> Reset => \"\\x1b[0m\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>DEC private mode: hide cursor.</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> HideCursor => \"\\x1b[?25l\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>DEC private mode: show cursor.</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> ShowCursor => \"\\x1b[?25h\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Erase line + CR (in-place repaint idiom).</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> ClearLine => \"\\x1b[2K\\r\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Erase screen + home cursor.</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> ClearScreen => \"\\x1b[2J\\x1b[H\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Enter the alternate screen buffer.</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> EnterAlternateScreen => \"\\x1b[?1049h\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Exit the alternate screen buffer.</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> ExitAlternateScreen => \"\\x1b[?1049l\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Default foreground (SGR 39).</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> ForegroundDefault => \"\\x1b[39m\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Default background (SGR 49).</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> BackgroundDefault => \"\\x1b[49m\";");
        sb.AppendLine();
    }

    private static void EmitColorApi(StringBuilder sb, EscapeEnumInfo color)
    {
        sb.AppendLine("    /// <summary>SGR foreground span for an 8-bit palette slot (value 0 → default fg).</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> Foreground(Color8Bit color) => color switch");
        sb.AppendLine("    {");
        foreach (var member in color.Members.Where(static m => m.Value is >= 30 and <= 37 or >= 90 and <= 97))
        {
            sb.AppendLine($"        Color8Bit.{member.Name} => \"\\x1b[{member.Value}m\",");
        }

        sb.AppendLine("        _ => ForegroundDefault,");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>SGR background span for an 8-bit palette slot (value 0 → default bg).</summary>");
        sb.AppendLine("    public static ReadOnlySpan<char> Background(Color8Bit color) => color switch");
        sb.AppendLine("    {");
        foreach (var member in color.Members.Where(static m => m.Value is >= 30 and <= 37 or >= 90 and <= 97))
        {
            sb.AppendLine($"        Color8Bit.{member.Name} => \"\\x1b[{member.Value + 10}m\",");
        }

        sb.AppendLine("        _ => BackgroundDefault,");
        sb.AppendLine("    };");
        sb.AppendLine();
        EmitRgbFormatters(sb);
    }

    private static void EmitRgbFormatters(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Max chars written by <see cref=\"FormatForeground\"/>/<see cref=\"FormatBackground\"/>.</summary>");
        sb.AppendLine("    public const int RgbFormatLength = 19;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Writes SGR 24-bit foreground <c>ESC[38;2;R;G;Bm</c> into");
        sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
        sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static int FormatForeground(byte r, byte g, byte b, Span<char> destination)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (destination.Length < RgbFormatLength) return -1;");
        sb.AppendLine("        destination[0] = '\\x1b';");
        sb.AppendLine("        destination[1] = '[';");
        sb.AppendLine("        destination[2] = '3';");
        sb.AppendLine("        destination[3] = '8';");
        sb.AppendLine("        destination[4] = ';';");
        sb.AppendLine("        destination[5] = '2';");
        sb.AppendLine("        destination[6] = ';';");
        sb.AppendLine("        int n = AppendU8(destination, 7, r);");
        sb.AppendLine("        destination[n++] = ';';");
        sb.AppendLine("        n = AppendU8(destination, n, g);");
        sb.AppendLine("        destination[n++] = ';';");
        sb.AppendLine("        n = AppendU8(destination, n, b);");
        sb.AppendLine("        destination[n++] = 'm';");
        sb.AppendLine("        return n;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Writes SGR 24-bit background <c>ESC[48;2;R;G;Bm</c> into");
        sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
        sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static int FormatBackground(byte r, byte g, byte b, Span<char> destination)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (destination.Length < RgbFormatLength) return -1;");
        sb.AppendLine("        destination[0] = '\\x1b';");
        sb.AppendLine("        destination[1] = '[';");
        sb.AppendLine("        destination[2] = '4';");
        sb.AppendLine("        destination[3] = '8';");
        sb.AppendLine("        destination[4] = ';';");
        sb.AppendLine("        destination[5] = '2';");
        sb.AppendLine("        destination[6] = ';';");
        sb.AppendLine("        int n = AppendU8(destination, 7, r);");
        sb.AppendLine("        destination[n++] = ';';");
        sb.AppendLine("        n = AppendU8(destination, n, g);");
        sb.AppendLine("        destination[n++] = ';';");
        sb.AppendLine("        n = AppendU8(destination, n, b);");
        sb.AppendLine("        destination[n++] = 'm';");
        sb.AppendLine("        return n;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Formats <paramref name=\"value\"/> (0–255) without leading zero suppression padding.</summary>");
        sb.AppendLine("    private static int AppendU8(Span<char> d, int n, byte value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value >= 100) d[n++] = (char)('0' + value / 100);");
        sb.AppendLine("        if (value >= 10) d[n++] = (char)('0' + (value / 10) % 10);");
        sb.AppendLine("        d[n++] = (char)('0' + value % 10);");
        sb.AppendLine("        return n;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatForeground\"/>.</summary>");
        sb.AppendLine("    public static string ForegroundRgb(byte r, byte g, byte b)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<char> buf = stackalloc char[RgbFormatLength];");
        sb.AppendLine("        int n = FormatForeground(r, g, b, buf);");
        sb.AppendLine("        return new string(buf[..n]);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatBackground\"/>.</summary>");
        sb.AppendLine("    public static string BackgroundRgb(byte r, byte g, byte b)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<char> buf = stackalloc char[RgbFormatLength];");
        sb.AppendLine("        int n = FormatBackground(r, g, b, buf);");
        sb.AppendLine("        return new string(buf[..n]);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitCursorApi(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Max chars written by the CSI formatters (escape + '[' + 10 digits + final).</summary>");
        sb.AppendLine("    public const int CsiFormatLength = 14;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Writes a cursor movement <c>ESC[n{A|B|C|D}</c> into");
        sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Counts below 1");
        sb.AppendLine("    ///     are clamped to the ECMA-48 default of 1. Returns the written char");
        sb.AppendLine("    ///     count, or -1 when the buffer is too small.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static int FormatMove(CursorDirection direction, int count, Span<char> destination)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (destination.Length < CsiFormatLength) return -1;");
        sb.AppendLine("        if (count < 1) count = 1;");
        sb.AppendLine("        destination[0] = '\\x1b';");
        sb.AppendLine("        destination[1] = '[';");
        sb.AppendLine("        char final = direction switch");
        sb.AppendLine("        {");
        sb.AppendLine("            CursorDirection.Up => 'A',");
        sb.AppendLine("            CursorDirection.Down => 'B',");
        sb.AppendLine("            CursorDirection.Forward => 'C',");
        sb.AppendLine("            _ => 'D',");
        sb.AppendLine("        };");
        sb.AppendLine("        int n = 2;");
        sb.AppendLine("        n = AppendI32(destination, n, count);");
        sb.AppendLine("        destination[n++] = final;");
        sb.AppendLine("        return n;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Writes CUP <c>ESC[row;colH</c> (1-based) into");
        sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
        sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static int FormatPosition(int row, int col, Span<char> destination)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (destination.Length < CsiFormatLength + 1) return -1;");
        sb.AppendLine("        if (row < 1) row = 1;");
        sb.AppendLine("        if (col < 1) col = 1;");
        sb.AppendLine("        destination[0] = '\\x1b';");
        sb.AppendLine("        destination[1] = '[';");
        sb.AppendLine("        int n = AppendI32(destination, 2, row);");
        sb.AppendLine("        destination[n++] = ';';");
        sb.AppendLine("        n = AppendI32(destination, n, col);");
        sb.AppendLine("        destination[n++] = 'H';");
        sb.AppendLine("        return n;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Formats a signed decimal integer without allocation.</summary>");
        sb.AppendLine("    private static int AppendI32(Span<char> d, int n, int value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            d[n++] = '0';");
        sb.AppendLine("            return n;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        Span<char> tmp = stackalloc char[11];");
        sb.AppendLine("        int t = 11;");
        sb.AppendLine("        bool negative = value < 0;");
        sb.AppendLine("        ulong v = negative ? (ulong)(-(long)value) : (ulong)value;");
        sb.AppendLine("        while (v > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            tmp[--t] = (char)('0' + (v % 10));");
        sb.AppendLine("            v /= 10;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (negative) d[n++] = '-';");
        sb.AppendLine("        tmp[t..].CopyTo(d[n..]);");
        sb.AppendLine("        return n + (11 - t);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatMove\"/>.</summary>");
        sb.AppendLine("    public static string Move(CursorDirection direction, int count)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<char> buf = stackalloc char[CsiFormatLength];");
        sb.AppendLine("        int n = FormatMove(direction, count, buf);");
        sb.AppendLine("        return new string(buf[..n]);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatPosition\"/>.</summary>");
        sb.AppendLine("    public static string Position(int row, int col)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<char> buf = stackalloc char[CsiFormatLength + 1];");
        sb.AppendLine("        int n = FormatPosition(row, col, buf);");
        sb.AppendLine("        return new string(buf[..n]);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitStyleApi(StringBuilder sb, EscapeEnumInfo style)
    {
        var names = new HashSet<string>(style.Members.Select(static m => m.Name));
        sb.AppendLine("    /// <summary>Max chars written by <see cref=\"FormatStyle\"/> (params + separators).</summary>");
        sb.AppendLine("    public const int StyleFormatLength = 11;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Writes the SGR decoration params (e.g. <c>1;4</c>) for");
        sb.AppendLine("    ///     <paramref name=\"style\"/> into <paramref name=\"destination\"/>");
        sb.AppendLine("    ///     without allocation. Returns the written char count (0 for");
        sb.AppendLine("    ///     <see cref=\"StyleFlag.None\"/>), or -1 when the buffer is too small.");
        sb.AppendLine("    /// </summary>");

        sb.AppendLine("    public static int FormatStyle(StyleFlag style, Span<char> destination)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (destination.Length < StyleFormatLength) return -1;");
        sb.AppendLine("        int n = 0;");
        AppendParam(sb, names, "Bold", "1");
        AppendParam(sb, names, "Dim", "2");
        AppendParam(sb, names, "Italic", "3");
        AppendParam(sb, names, "Underline", "4");
        AppendParam(sb, names, "Strike", "9");
        AppendParam(sb, names, "Reverse", "7");
        sb.AppendLine("        return n;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatStyle\"/>.</summary>");
        sb.AppendLine("    public static string Style(StyleFlag style)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<char> buf = stackalloc char[StyleFormatLength];");
        sb.AppendLine("        int n = FormatStyle(style, buf);");
        sb.AppendLine("        return n == 0 ? string.Empty : new string(buf[..n]);");
        sb.AppendLine("    }");
        sb.AppendLine();

        void AppendParam(StringBuilder s, HashSet<string> presentNames, string member, string code)
        {
            if (!presentNames.Contains(member))
            {
                return;
            }

            s.AppendLine($"        if ((style & StyleFlag.{member}) != 0)");
            s.AppendLine("        {");
            s.AppendLine("            if (n > 0) destination[n++] = ';';");
            s.AppendLine($"            destination[n++] = '{code}';");
            s.AppendLine("        }");
            s.AppendLine();
        }
    }

    private static string Sanitize(string ns)
    {
        var sb = new StringBuilder(ns.Length);
        foreach (var c in ns)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return sb.ToString();
    }
}

/// <summary>Equatable snapshot of a [TerminalEscape] enum for the incremental pipeline.</summary>
internal sealed class EscapeEnumInfo : IEquatable<EscapeEnumInfo>
{
    public EscapeEnumInfo(string name, string ns, ImmutableArray<(string Name, int Value)> members)
    {
        Name = name;
        Namespace = ns;
        Members = members;
    }

    public string Name { get; }

    public string Namespace { get; }

    public ImmutableArray<(string Name, int Value)> Members { get; }

    public bool Equals(EscapeEnumInfo? other) =>
        other is not null
        && Name == other.Name
        && Namespace == other.Namespace
        && Members.Length == other.Members.Length
        && Members.SequenceEqual(other.Members);

    public override bool Equals(object? obj) => Equals(obj as EscapeEnumInfo);

    public override int GetHashCode()
    {
        unchecked
        {
            int hash = Name.GetHashCode() * 397;
            hash ^= Namespace.GetHashCode();
            foreach (var (name, value) in Members)
            {
                hash = (hash * 31) ^ name.GetHashCode();
                hash = (hash * 31) ^ value;
            }

            return hash;
        }
    }

    public static EscapeEnumInfo Create(INamedTypeSymbol enumSymbol)
    {
        var members = ImmutableArray.CreateBuilder<(string Name, int Value)>();
        foreach (var member in enumSymbol.GetMembers())
        {
            if (member is IFieldSymbol { ConstantValue: not null } field)
            {
                members.Add((field.Name, (int)field.ConstantValue!));
            }
        }

        return new EscapeEnumInfo(enumSymbol.Name, enumSymbol.ContainingNamespace.ToDisplayString(), members.ToImmutable());
    }
}
