<<<<<<< HEAD
using System.Collections.Immutable;
using System.Text;
=======
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Harbor.Abstractions.Contracts;
>>>>>>> sprint/codegen-boilerplate
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

<<<<<<< HEAD
/// <summary>Attribute to mark enums for escape code generation by EscapeCodeGenerator.</summary>
[AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
public sealed class TerminalEscapeAttribute : Attribute
{
    /// <summary>Initializes a new instance of the TerminalEscapeAttribute class.</summary>
    public TerminalEscapeAttribute()
    {
    }
}

=======
>>>>>>> sprint/codegen-boilerplate
[Generator]
public sealed class EscapeCodeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
<<<<<<< HEAD
        var escapeEnums = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Harbor.CodeGen.TerminalEscapeAttribute",
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.EnumDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var allEnums = escapeEnums.Collect();

        context.RegisterSourceOutput(allEnums, static (spc, symbols) =>
        {
            if (symbols.Length == 0) return;

            var ns = symbols[0].ContainingNamespace.ToDisplayString();
            var source = GenerateEscapeCodes(ns, symbols);
            spc.AddSource($"EscapeCodes_{ns.Replace('.', '_')}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateEscapeCodes(string ns, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.EscapeCodeGenerator from [TerminalEscape] enums.");
        sb.AppendLine("// Zero-allocation ECMA-48 tables — do not edit; hand-written literals belong in EscapeCodeStrategy.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated ECMA-48 escape-code tables (source: [TerminalEscape] enums).</summary>");
        sb.AppendLine("public static class EscapeCodes");
        sb.AppendLine("{");

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var symbol in symbols)
        {
            var enumName = symbol.Name;
            var members = symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.ConstantValue is not null)
                .Select(f => f.Name)
                .ToArray();

            AppendEnumTable(sb, enumName, members, emitted);
=======
        var enumSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.EnumDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!)
            .Where(static e => e.GetAttributes().Any(ad => ad.AttributeClass?.Name == nameof(TerminalEscapeAttribute)))
            .Select(static (enumSymbol, _) =>
            {
                var enumName = enumSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var @namespace = enumSymbol.ContainingNamespace.ToDisplayString();

                var attrData = enumSymbol.GetAttributes()
                    .FirstOrDefault(ad => ad.AttributeClass?.Name == nameof(TerminalEscapeAttribute));
                string className = $"{enumName}EscapeCodes";
                string? ns = null;
                string resetMember = "Reset";

                if (attrData is not null)
                {
                    foreach (var na in attrData.NamedArguments)
                    {
                        switch (na.Key)
                        {
                            case nameof(TerminalEscapeAttribute.ClassName):
                                className = na.Value.Value?.ToString() ?? className;
                                break;
                            case nameof(TerminalEscapeAttribute.Namespace):
                                ns = na.Value.Value?.ToString();
                                break;
                            case nameof(TerminalEscapeAttribute.ResetMember):
                                resetMember = na.Value.Value?.ToString() ?? resetMember;
                                break;
                        }
                    }
                }

                var members = enumSymbol.GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(f => f.HasConstantValue && f.ConstantValue is byte or sbyte or short or int)
                    .Select(f => (Name: f.Name, Value: Convert.ToByte(f.ConstantValue)))
                    .OrderBy(m => m.Value)
                    .ToArray();

                return (
                    EnumName: enumName,
                    Namespace: ns ?? @namespace,
                    ClassName: className,
                    ResetMember: resetMember,
                    Members: members,
                    Kind: DetectKind(enumName)
                );
            })
            .Where(static data => data.Members.Length > 0);

        context.RegisterSourceOutput(enumSymbols, static (spc, data) =>
        {
            spc.AddSource($"EscapeCodes_{Sanitize(data.Namespace)}_{data.ClassName}.g.cs", SourceText.From(GenerateClass(data), Encoding.UTF8));
        });
    }

    private static string Sanitize(string s) => s.Replace('.', '_').Replace('+', '_').Replace('<', '_').Replace('>', '_');

    private static EscapeKind DetectKind(string enumName) => enumName switch
    {
        "StyleFlag" => EscapeKind.Style,
        "CursorDirection" => EscapeKind.Cursor,
        "Color8Bit" => EscapeKind.Color8Bit,
        _ => EscapeKind.Generic
    };

    private enum EscapeKind { Style, Cursor, Color8Bit, Generic }

    private static string GenerateClass((string EnumName, string Namespace, string ClassName, string ResetMember, (string Name, byte Value)[] Members, EscapeKind Kind) data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// EscapeCodeGenerator — DO NOT EDIT");
        sb.AppendLine($"namespace {data.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"///     Precomputed escape-code strings for <see cref=\"{data.EnumName}\" />.");
        sb.AppendLine("///     Generated by <see cref=\"EscapeCodeGenerator\" /> — zero allocations on hot paths.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class " + data.ClassName);
        sb.AppendLine("{");

        if (data.Kind == EscapeKind.Style)
        {
            GenerateStyleCode(sb, data);
        }
        else if (data.Kind == EscapeKind.Cursor)
        {
            GenerateCursorCode(sb, data);
        }
        else if (data.Kind == EscapeKind.Color8Bit)
        {
            GenerateColorCode(sb, data);
        }
        else
        {
            GenerateGenericCode(sb, data);
>>>>>>> sprint/codegen-boilerplate
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

<<<<<<< HEAD
    private static void AppendEnumTable(StringBuilder sb, string enumName, string[] members, HashSet<string> emitted)
    {
        switch (enumName)
        {
            case "Color8Bit":
                if (emitted.Add("Reset"))
                {
                    sb.AppendLine("    /// <summary>SGR reset — all attributes off.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> Reset => \"\\x1b[0m\";");
                    sb.AppendLine();
                }
                if (emitted.Add("HideCursor"))
                {
                    sb.AppendLine("    /// <summary>DEC private mode: hide cursor.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> HideCursor => \"\\x1b[?25l\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ShowCursor"))
                {
                    sb.AppendLine("    /// <summary>DEC private mode: show cursor.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ShowCursor => \"\\x1b[?25h\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ClearLine"))
                {
                    sb.AppendLine("    /// <summary>Erase line + CR (in-place repaint idiom).</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ClearLine => \"\\x1b[2K\\r\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ClearScreen"))
                {
                    sb.AppendLine("    /// <summary>Erase screen + home cursor.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ClearScreen => \"\\x1b[2J\\x1b[H\";");
                    sb.AppendLine();
                }
                if (emitted.Add("EnterAlternateScreen"))
                {
                    sb.AppendLine("    /// <summary>Enter the alternate screen buffer.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> EnterAlternateScreen => \"\\x1b[?1049h\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ExitAlternateScreen"))
                {
                    sb.AppendLine("    /// <summary>Exit the alternate screen buffer.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ExitAlternateScreen => \"\\x1b[?1049l\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ForegroundDefault"))
                {
                    sb.AppendLine("    /// <summary>Default foreground (SGR 39).</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ForegroundDefault => \"\\x1b[39m\";");
                    sb.AppendLine();
                }
                if (emitted.Add("BackgroundDefault"))
                {
                    sb.AppendLine("    /// <summary>Default background (SGR 49).</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> BackgroundDefault => \"\\x1b[49m\";");
                    sb.AppendLine();
                }
                sb.AppendLine("    /// <summary>SGR foreground span for an 8-bit palette slot (value 0 → default fg).</summary>");
                sb.AppendLine("    public static ReadOnlySpan<char> Foreground(Color8Bit color) => color switch");
                sb.AppendLine("    {");
                foreach (var m in members)
                {
                    if (m == "Default") continue;
                    var code = ColorCode(m, isForeground: true);
                    sb.AppendLine($"        Color8Bit.{m} => \"\\x1b[{code}m\",");
                }
                sb.AppendLine("        _ => ForegroundDefault,");
                sb.AppendLine("    };");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>SGR background span for an 8-bit palette slot (value 0 → default bg).</summary>");
                sb.AppendLine("    public static ReadOnlySpan<char> Background(Color8Bit color) => color switch");
                sb.AppendLine("    {");
                foreach (var m in members)
                {
                    if (m == "Default") continue;
                    var code = ColorCode(m, isForeground: false);
                    sb.AppendLine($"        Color8Bit.{m} => \"\\x1b[{code}m\",");
                }
                sb.AppendLine("        _ => BackgroundDefault,");
                sb.AppendLine("    };");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Max chars written by <see cref=\"FormatForeground\"/>/<see cref=\"FormatBackground\"/>.</summary>");
                sb.AppendLine("    public const int RgbFormatLength = 19;");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    ///     Writes SGR 24-bit foreground <c>ESC[38;2;R;G;Bm</c> into");
                sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
                sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static int FormatForeground(byte r, byte g, byte b, Span<char> destination)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (destination.Length < RgbFormatLength) return -1;");
                sb.AppendLine("        destination[0] = '\\x1b';");
                sb.AppendLine("        destination[1] = '[';");
                sb.AppendLine("        destination[2] = '3';");
                sb.AppendLine("        destination[3] = '8';");
                sb.AppendLine("        destination[4] = ';';");
                sb.AppendLine("        destination[5] = '2';");
                sb.AppendLine("        destination[6] = ';';");
                sb.AppendLine("        int n = AppendU8(destination, 7, r);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, g);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, b);");
                sb.AppendLine("        destination[n++] = 'm';");
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    ///     Writes SGR 24-bit background <c>ESC[48;2;R;G;Bm</c> into");
                sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
                sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static int FormatBackground(byte r, byte g, byte b, Span<char> destination)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (destination.Length < RgbFormatLength) return -1;");
                sb.AppendLine("        destination[0] = '\\x1b';");
                sb.AppendLine("        destination[1] = '[';");
                sb.AppendLine("        destination[2] = '4';");
                sb.AppendLine("        destination[3] = '8';");
                sb.AppendLine("        destination[4] = ';';");
                sb.AppendLine("        destination[5] = '2';");
                sb.AppendLine("        destination[6] = ';';");
                sb.AppendLine("        int n = AppendU8(destination, 7, r);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, g);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, b);");
                sb.AppendLine("        destination[n++] = 'm';");
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Formats <paramref name=\"value\"/> (0–255) without leading zero suppression padding.</summary>");
                sb.AppendLine("    private static int AppendU8(Span<char> d, int n, byte value)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (value >= 100) d[n++] = (char)('0' + value / 100);");
                sb.AppendLine("        if (value >= 10) d[n++] = (char)('0' + (value / 10) % 10);");
                sb.AppendLine("        d[n++] = (char)('0' + value % 10);");
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatForeground\"/>.</summary>");
                sb.AppendLine("    public static string ForegroundRgb(byte r, byte g, byte b)");
                sb.AppendLine("    {");
                sb.AppendLine("        Span<char> buf = stackalloc char[RgbFormatLength];");
                sb.AppendLine("        int n = FormatForeground(r, g, b, buf);");
                sb.AppendLine("        return new string(buf[..n]);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatBackground\"/>.</summary>");
                sb.AppendLine("    public static string BackgroundRgb(byte r, byte g, byte b)");
                sb.AppendLine("    {");
                sb.AppendLine("        Span<char> buf = stackalloc char[RgbFormatLength];");
                sb.AppendLine("        int n = FormatBackground(r, g, b, buf);");
                sb.AppendLine("        return new string(buf[..n]);");
                sb.AppendLine("    }");
                sb.AppendLine();
                break;

            case "CursorDirection":
                if (emitted.Add("CsiFormatLength"))
                {
                    sb.AppendLine("    /// <summary>Max chars written by the CSI formatters (escape + '[' + 10 digits + final).</summary>");
                    sb.AppendLine("    public const int CsiFormatLength = 14;");
                    sb.AppendLine();
                }
                if (emitted.Add("FormatMove"))
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine("    ///     Writes a cursor movement <c>ESC[n{A|B|C|D}</c> into");
                    sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Counts below 1");
                    sb.AppendLine("    ///     are clamped to the ECMA-48 default of 1. Returns the written char");
                    sb.AppendLine("    ///     count, or -1 when the buffer is too small.");
                    sb.AppendLine("    /// </summary>");
                    sb.AppendLine("    public static int FormatMove(CursorDirection direction, int count, Span<char> destination)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (destination.Length < CsiFormatLength) return -1;");
                    sb.AppendLine("        if (count < 1) count = 1;");
                    sb.AppendLine("        destination[0] = '\\x1b';");
                    sb.AppendLine("        destination[1] = '[';");
                    sb.AppendLine("        char final = direction switch");
                    sb.AppendLine("        {");
                    sb.AppendLine("            CursorDirection.Up => 'A',");
                    sb.AppendLine("            CursorDirection.Down => 'B',");
                    sb.AppendLine("            CursorDirection.Forward => 'C',");
                    sb.AppendLine("            _ => 'D',");
                    sb.AppendLine("        };");
                    sb.AppendLine("        int n = 2;");
                    sb.AppendLine("        n = AppendI32(destination, n, count);");
                    sb.AppendLine("        destination[n++] = final;");
                    sb.AppendLine("        return n;");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("Move"))
                {
                    sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatMove\"/>.</summary>");
                    sb.AppendLine("    public static string Move(CursorDirection direction, int count)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        Span<char> buf = stackalloc char[CsiFormatLength];");
                    sb.AppendLine("        int n = FormatMove(direction, count, buf);");
                    sb.AppendLine("        return new string(buf[..n]);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("AppendI32"))
                {
                    sb.AppendLine("    /// <summary>Formats a signed decimal integer without allocation.</summary>");
                    sb.AppendLine("    private static int AppendI32(Span<char> d, int n, int value)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (value == 0)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            d[n++] = '0';");
                    sb.AppendLine("            return n;");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        Span<char> tmp = stackalloc char[11];");
                    sb.AppendLine("        int t = 11;");
                    sb.AppendLine("        bool negative = value < 0;");
                    sb.AppendLine("        ulong v = negative ? (ulong)(-(long)value) : (ulong)value;");
                    sb.AppendLine("        while (v > 0)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            tmp[--t] = (char)('0' + (v % 10));");
                    sb.AppendLine("            v /= 10;");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        if (negative) d[n++] = '-';");
                    sb.AppendLine("        tmp[t..].CopyTo(d[n..]);");
                    sb.AppendLine("        return n + (11 - t);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("FormatPosition"))
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine("    ///     Writes CUP <c>ESC[row;colH</c> (1-based) into");
                    sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
                    sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
                    sb.AppendLine("    /// </summary>");
                    sb.AppendLine("    public static int FormatPosition(int row, int col, Span<char> destination)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (destination.Length < CsiFormatLength + 1) return -1;");
                    sb.AppendLine("        if (row < 1) row = 1;");
                    sb.AppendLine("        if (col < 1) col = 1;");
                    sb.AppendLine("        destination[0] = '\\x1b';");
                    sb.AppendLine("        destination[1] = '[';");
                    sb.AppendLine("        int n = AppendI32(destination, 2, row);");
                    sb.AppendLine("        destination[n++] = ';';");
                    sb.AppendLine("        n = AppendI32(destination, n, col);");
                    sb.AppendLine("        destination[n++] = 'H';");
                    sb.AppendLine("        return n;");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("Position"))
                {
                    sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatPosition\"/>.</summary>");
                    sb.AppendLine("    public static string Position(int row, int col)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        Span<char> buf = stackalloc char[CsiFormatLength + 1];");
                    sb.AppendLine("        int n = FormatPosition(row, col, buf);");
                    sb.AppendLine("        return new string(buf[..n]);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                break;

            case "StyleFlag":
                if (emitted.Add("StyleFormatLength"))
                {
                    sb.AppendLine("    /// <summary>Max chars written by <see cref=\"FormatStyle\"/> (params + separators).</summary>");
                    sb.AppendLine("    public const int StyleFormatLength = 11;");
                    sb.AppendLine();
                }
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    ///     Writes the SGR decoration params (e.g. <c>1;4</c>) for");
                sb.AppendLine("    ///     <paramref name=\"style\"/> into <paramref name=\"destination\"/>");
                sb.AppendLine("    ///     without allocation. Returns the written char count (0 for");
                sb.AppendLine("    ///     <see cref=\"StyleFlag.None\"/>), or -1 when the buffer is too small.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static int FormatStyle(StyleFlag style, Span<char> destination)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (destination.Length < StyleFormatLength) return -1;");
                sb.AppendLine("        int n = 0;");
                foreach (var m in members)
                {
                    if (m == "None") continue;
                    var code = StyleCode(m);
                    sb.AppendLine($"        if ((style & StyleFlag.{m}) != 0)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            if (n > 0) destination[n++] = ';';");
                    sb.AppendLine($"            destination[n++] = '{code}';");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatStyle\"/>.</summary>");
                sb.AppendLine("    public static string Style(StyleFlag style)");
                sb.AppendLine("    {");
                sb.AppendLine("        Span<char> buf = stackalloc char[StyleFormatLength];");
                sb.AppendLine("        int n = FormatStyle(style, buf);");
                sb.AppendLine("        return n == 0 ? string.Empty : new string(buf[..n]);");
                sb.AppendLine("    }");
                sb.AppendLine();
                break;
        }
    }

    private static string ColorCode(string member, bool isForeground)
    {
        return member switch
        {
            "Black" => isForeground ? "30" : "40",
            "Red" => isForeground ? "31" : "41",
            "Green" => isForeground ? "32" : "42",
            "Yellow" => isForeground ? "33" : "43",
            "Blue" => isForeground ? "34" : "44",
            "Magenta" => isForeground ? "35" : "45",
            "Cyan" => isForeground ? "36" : "46",
            "White" => isForeground ? "37" : "47",
            "BrightBlack" => isForeground ? "90" : "100",
            "BrightRed" => isForeground ? "91" : "101",
            "BrightGreen" => isForeground ? "92" : "102",
            "BrightYellow" => isForeground ? "93" : "103",
            "BrightBlue" => isForeground ? "94" : "104",
            "BrightMagenta" => isForeground ? "95" : "105",
            "BrightCyan" => isForeground ? "96" : "106",
            "BrightWhite" => isForeground ? "97" : "107",
            _ => isForeground ? "39" : "49",
        };
    }

    private static string StyleCode(string member)
    {
        return member switch
        {
            "Bold" => "1",
            "Dim" => "2",
            "Italic" => "3",
            "Underline" => "4",
            "Strike" => "9",
            "Reverse" => "7",
            _ => "0",
        };
    }
=======
    private static void GenerateStyleCode(StringBuilder sb, (string EnumName, string Namespace, string ClassName, string ResetMember, (string Name, byte Value)[] Members, EscapeKind Kind) data)
    {
        sb.AppendLine("    // Precomputed SGR parameter strings");
        foreach (var m in data.Members)
        {
            if (m.Name == "Reset")
            {
                sb.AppendLine($"    public const string {m.Name} = \"\\x1b[0m\";");
            }
            else
            {
                sb.AppendLine($"    public const string {m.Name} = \"\\x1b[{m.Value}m\";");
            }
        }

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Combine multiple <see cref=\"{data.EnumName}\" /> flags into one SGR sequence.</summary>");
        sb.AppendLine($"    public static string Combine({data.EnumName} flags)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (flags == 0) return Reset;");
        sb.AppendLine("        var codes = new System.Text.StringBuilder(16);");
        sb.AppendLine("        bool first = true;");
        sb.AppendLine("        foreach (" + data.EnumName + " f in System.Enum.GetValues(typeof(" + data.EnumName + ")))");
        sb.AppendLine("        {");
        sb.AppendLine("            if (f == " + data.EnumName + ".Reset) continue;");
        sb.AppendLine("            if ((flags & f) == 0) continue;");
        sb.AppendLine("            if (!first) codes.Append(';');");
        sb.AppendLine("            codes.Append((int)f);");
        sb.AppendLine("            first = false;");
        sb.AppendLine("        }");
        sb.AppendLine("        return codes.Length == 0 ? Reset : $\"\\x1b[{codes}m\";");
        sb.AppendLine("    }");
    }

    private static void GenerateCursorCode(StringBuilder sb, (string EnumName, string Namespace, string ClassName, string ResetMember, (string Name, byte Value)[] Members, EscapeKind Kind) data)
    {
        var csiMap = new Dictionary<string, byte>
        {
            ["Up"] = (byte)'A', ["Down"] = (byte)'B', ["Forward"] = (byte)'C',
            ["Back"] = (byte)'D', ["NextLine"] = (byte)'E', ["PreviousLine"] = (byte)'F',
            ["HorizontalAbsolute"] = (byte)'G', ["Position"] = (byte)'H',
            ["EraseDisplay"] = (byte)'J', ["EraseLine"] = (byte)'K',
            ["ScrollUp"] = (byte)'S', ["ScrollDown"] = (byte)'T',
            ["Save"] = (byte)'s', ["Restore"] = (byte)'u',
        };

        sb.AppendLine("    /// <summary>Build a CSI sequence for <paramref name=\"direction\" /> with optional <paramref name=\"count\" />.</summary>");
        sb.AppendLine("    public static string Cursor(CursorDirection direction, int count = 1)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (count <= 0) return string.Empty;");
        sb.AppendLine("        char final = direction switch");
        sb.AppendLine("        {");
        foreach (var m in data.Members.OrderBy(m => m.Value))
        {
            byte finalByte = csiMap.GetValueOrDefault(m.Name, (byte)' ');
            sb.AppendLine($"            {data.EnumName}.{m.Name} => '{(char)finalByte}',");
        }
        sb.AppendLine("            _ => ' '");
        sb.AppendLine("        };");
        sb.AppendLine("        return count == 1 ? $\"\\x1b[{final}\" : $\"\\x1b[{count}{final}\";");
        sb.AppendLine("    }");
    }

    private static void GenerateColorCode(StringBuilder sb, (string EnumName, string Namespace, string ClassName, string ResetMember, (string Name, byte Value)[] Members, EscapeKind Kind) data)
    {
        sb.AppendLine("    /// <summary>ESC [ 38;5;{n} m — set foreground to palette color.</summary>");
        sb.AppendLine("    public static string Foreground(Color8Bit color)");
        sb.AppendLine("    {");
        sb.AppendLine("        return color switch");
        sb.AppendLine("        {");
        foreach (var m in data.Members.OrderBy(m => m.Value))
        {
            sb.AppendLine($"            {data.EnumName}.{m.Name} => $\"\\x1b[38;5;{(int)m.Value}m\",");
        }
        sb.AppendLine("            _ => $\"\\x1b[38;5;{(int)color}m\"");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>ESC [ 48;5;{n} m — set background to palette color.</summary>");
        sb.AppendLine("    public static string Background(Color8Bit color)");
        sb.AppendLine("    {");
        sb.AppendLine("        return color switch");
        sb.AppendLine("        {");
        foreach (var m in data.Members.OrderBy(m => m.Value))
        {
            sb.AppendLine($"            {data.EnumName}.{m.Name} => $\"\\x1b[48;5;{(int)m.Value}m\",");
        }
        sb.AppendLine("            _ => $\"\\x1b[48;5;{(int)color}m\"");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void GenerateGenericCode(StringBuilder sb, (string EnumName, string Namespace, string ClassName, string ResetMember, (string Name, byte Value)[] Members, EscapeKind Kind) data)
    {
        foreach (var m in data.Members)
        {
            sb.AppendLine($"    public const string {m.Name} = \"\\x1b[{(m.Value == 0 ? 0 : m.Value)}m\";");
        }
    }
>>>>>>> sprint/codegen-boilerplate
}
