using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>Attribute to mark enums for escape code generation by EscapeCodeGenerator.</summary>
[AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
public sealed class TerminalEscapeAttribute : Attribute
{
    /// <summary>Initializes a new instance of the TerminalEscapeAttribute class.</summary>
    public TerminalEscapeAttribute()
    {
    }
}

[Generator]
public sealed class EscapeCodeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var escapeEnums = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Harbor.CodeGen.TerminalEscapeAttribute",
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.EnumDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var allEnums = escapeEnums.Collect();

        context.RegisterSourceOutput(allEnums, static (spc, symbols) =>
        {
            if (symbols.Length == 0) return;

            var ns = symbols[0].ContainingNamespace.ToDisplayString();
            var source = GenerateEscapeCodes(ns, symbols);
            spc.AddSource($"EscapeCodes_{ns.Replace('.', '_')}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateEscapeCodes(string ns, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.EscapeCodeGenerator from [TerminalEscape] enums.");
        sb.AppendLine("// Zero-allocation ECMA-48 tables — do not edit; hand-written literals belong in EscapeCodeStrategy.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated ECMA-48 escape-code tables (source: [TerminalEscape] enums).</summary>");
        sb.AppendLine("public static class EscapeCodes");
        sb.AppendLine("{");

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var symbol in symbols)
        {
            var enumName = symbol.Name;
            var members = symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f.ConstantValue is not null)
                .Select(f => f.Name)
                .ToArray();

            AppendEnumTable(sb, enumName, members, emitted);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendEnumTable(StringBuilder sb, string enumName, string[] members, HashSet<string> emitted)
    {
        switch (enumName)
        {
            case "Color8Bit":
                if (emitted.Add("Reset"))
                {
                    sb.AppendLine("    /// <summary>SGR reset — all attributes off.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> Reset => \"\\x1b[0m\";");
                    sb.AppendLine();
                }
                if (emitted.Add("HideCursor"))
                {
                    sb.AppendLine("    /// <summary>DEC private mode: hide cursor.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> HideCursor => \"\\x1b[?25l\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ShowCursor"))
                {
                    sb.AppendLine("    /// <summary>DEC private mode: show cursor.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ShowCursor => \"\\x1b[?25h\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ClearLine"))
                {
                    sb.AppendLine("    /// <summary>Erase line + CR (in-place repaint idiom).</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ClearLine => \"\\x1b[2K\\r\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ClearScreen"))
                {
                    sb.AppendLine("    /// <summary>Erase screen + home cursor.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ClearScreen => \"\\x1b[2J\\x1b[H\";");
                    sb.AppendLine();
                }
                if (emitted.Add("EnterAlternateScreen"))
                {
                    sb.AppendLine("    /// <summary>Enter the alternate screen buffer.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> EnterAlternateScreen => \"\\x1b[?1049h\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ExitAlternateScreen"))
                {
                    sb.AppendLine("    /// <summary>Exit the alternate screen buffer.</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ExitAlternateScreen => \"\\x1b[?1049l\";");
                    sb.AppendLine();
                }
                if (emitted.Add("ForegroundDefault"))
                {
                    sb.AppendLine("    /// <summary>Default foreground (SGR 39).</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> ForegroundDefault => \"\\x1b[39m\";");
                    sb.AppendLine();
                }
                if (emitted.Add("BackgroundDefault"))
                {
                    sb.AppendLine("    /// <summary>Default background (SGR 49).</summary>");
                    sb.AppendLine("    public static ReadOnlySpan<char> BackgroundDefault => \"\\x1b[49m\";");
                    sb.AppendLine();
                }
                sb.AppendLine("    /// <summary>SGR foreground span for an 8-bit palette slot (value 0 → default fg).</summary>");
                sb.AppendLine("    public static ReadOnlySpan<char> Foreground(Color8Bit color) => color switch");
                sb.AppendLine("    {");
                foreach (var m in members)
                {
                    if (m == "Default") continue;
                    var code = ColorCode(m, isForeground: true);
                    sb.AppendLine($"        Color8Bit.{m} => \"\\x1b[{code}m\",");
                }
                sb.AppendLine("        _ => ForegroundDefault,");
                sb.AppendLine("    };");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>SGR background span for an 8-bit palette slot (value 0 → default bg).</summary>");
                sb.AppendLine("    public static ReadOnlySpan<char> Background(Color8Bit color) => color switch");
                sb.AppendLine("    {");
                foreach (var m in members)
                {
                    if (m == "Default") continue;
                    var code = ColorCode(m, isForeground: false);
                    sb.AppendLine($"        Color8Bit.{m} => \"\\x1b[{code}m\",");
                }
                sb.AppendLine("        _ => BackgroundDefault,");
                sb.AppendLine("    };");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Max chars written by <see cref=\"FormatForeground\"/>/<see cref=\"FormatBackground\"/>.</summary>");
                sb.AppendLine("    public const int RgbFormatLength = 19;");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    ///     Writes SGR 24-bit foreground <c>ESC[38;2;R;G;Bm</c> into");
                sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
                sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static int FormatForeground(byte r, byte g, byte b, Span<char> destination)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (destination.Length < RgbFormatLength) return -1;");
                sb.AppendLine("        destination[0] = '\\x1b';");
                sb.AppendLine("        destination[1] = '[';");
                sb.AppendLine("        destination[2] = '3';");
                sb.AppendLine("        destination[3] = '8';");
                sb.AppendLine("        destination[4] = ';';");
                sb.AppendLine("        destination[5] = '2';");
                sb.AppendLine("        destination[6] = ';';");
                sb.AppendLine("        int n = AppendU8(destination, 7, r);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, g);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, b);");
                sb.AppendLine("        destination[n++] = 'm';");
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    ///     Writes SGR 24-bit background <c>ESC[48;2;R;G;Bm</c> into");
                sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
                sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static int FormatBackground(byte r, byte g, byte b, Span<char> destination)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (destination.Length < RgbFormatLength) return -1;");
                sb.AppendLine("        destination[0] = '\\x1b';");
                sb.AppendLine("        destination[1] = '[';");
                sb.AppendLine("        destination[2] = '4';");
                sb.AppendLine("        destination[3] = '8';");
                sb.AppendLine("        destination[4] = ';';");
                sb.AppendLine("        destination[5] = '2';");
                sb.AppendLine("        destination[6] = ';';");
                sb.AppendLine("        int n = AppendU8(destination, 7, r);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, g);");
                sb.AppendLine("        destination[n++] = ';';");
                sb.AppendLine("        n = AppendU8(destination, n, b);");
                sb.AppendLine("        destination[n++] = 'm';");
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Formats <paramref name=\"value\"/> (0–255) without leading zero suppression padding.</summary>");
                sb.AppendLine("    private static int AppendU8(Span<char> d, int n, byte value)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (value >= 100) d[n++] = (char)('0' + value / 100);");
                sb.AppendLine("        if (value >= 10) d[n++] = (char)('0' + (value / 10) % 10);");
                sb.AppendLine("        d[n++] = (char)('0' + value % 10);");
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatForeground\"/>.</summary>");
                sb.AppendLine("    public static string ForegroundRgb(byte r, byte g, byte b)");
                sb.AppendLine("    {");
                sb.AppendLine("        Span<char> buf = stackalloc char[RgbFormatLength];");
                sb.AppendLine("        int n = FormatForeground(r, g, b, buf);");
                sb.AppendLine("        return new string(buf[..n]);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatBackground\"/>.</summary>");
                sb.AppendLine("    public static string BackgroundRgb(byte r, byte g, byte b)");
                sb.AppendLine("    {");
                sb.AppendLine("        Span<char> buf = stackalloc char[RgbFormatLength];");
                sb.AppendLine("        int n = FormatBackground(r, g, b, buf);");
                sb.AppendLine("        return new string(buf[..n]);");
                sb.AppendLine("    }");
                sb.AppendLine();
                break;

            case "CursorDirection":
                if (emitted.Add("CsiFormatLength"))
                {
                    sb.AppendLine("    /// <summary>Max chars written by the CSI formatters (escape + '[' + 10 digits + final).</summary>");
                    sb.AppendLine("    public const int CsiFormatLength = 14;");
                    sb.AppendLine();
                }
                if (emitted.Add("FormatMove"))
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine("    ///     Writes a cursor movement <c>ESC[n{A|B|C|D}</c> into");
                    sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Counts below 1");
                    sb.AppendLine("    ///     are clamped to the ECMA-48 default of 1. Returns the written char");
                    sb.AppendLine("    ///     count, or -1 when the buffer is too small.");
                    sb.AppendLine("    /// </summary>");
                    sb.AppendLine("    public static int FormatMove(CursorDirection direction, int count, Span<char> destination)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (destination.Length < CsiFormatLength) return -1;");
                    sb.AppendLine("        if (count < 1) count = 1;");
                    sb.AppendLine("        destination[0] = '\\x1b';");
                    sb.AppendLine("        destination[1] = '[';");
                    sb.AppendLine("        char final = direction switch");
                    sb.AppendLine("        {");
                    sb.AppendLine("            CursorDirection.Up => 'A',");
                    sb.AppendLine("            CursorDirection.Down => 'B',");
                    sb.AppendLine("            CursorDirection.Forward => 'C',");
                    sb.AppendLine("            _ => 'D',");
                    sb.AppendLine("        };");
                    sb.AppendLine("        int n = 2;");
                    sb.AppendLine("        n = AppendI32(destination, n, count);");
                    sb.AppendLine("        destination[n++] = final;");
                    sb.AppendLine("        return n;");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("Move"))
                {
                    sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatMove\"/>.</summary>");
                    sb.AppendLine("    public static string Move(CursorDirection direction, int count)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        Span<char> buf = stackalloc char[CsiFormatLength];");
                    sb.AppendLine("        int n = FormatMove(direction, count, buf);");
                    sb.AppendLine("        return new string(buf[..n]);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("AppendI32"))
                {
                    sb.AppendLine("    /// <summary>Formats a signed decimal integer without allocation.</summary>");
                    sb.AppendLine("    private static int AppendI32(Span<char> d, int n, int value)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (value == 0)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            d[n++] = '0';");
                    sb.AppendLine("            return n;");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        Span<char> tmp = stackalloc char[11];");
                    sb.AppendLine("        int t = 11;");
                    sb.AppendLine("        bool negative = value < 0;");
                    sb.AppendLine("        ulong v = negative ? (ulong)(-(long)value) : (ulong)value;");
                    sb.AppendLine("        while (v > 0)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            tmp[--t] = (char)('0' + (v % 10));");
                    sb.AppendLine("            v /= 10;");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        if (negative) d[n++] = '-';");
                    sb.AppendLine("        tmp[t..].CopyTo(d[n..]);");
                    sb.AppendLine("        return n + (11 - t);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("FormatPosition"))
                {
                    sb.AppendLine("    /// <summary>");
                    sb.AppendLine("    ///     Writes CUP <c>ESC[row;colH</c> (1-based) into");
                    sb.AppendLine("    ///     <paramref name=\"destination\"/> without allocation. Returns the");
                    sb.AppendLine("    ///     written char count, or -1 when the buffer is too small.");
                    sb.AppendLine("    /// </summary>");
                    sb.AppendLine("    public static int FormatPosition(int row, int col, Span<char> destination)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (destination.Length < CsiFormatLength + 1) return -1;");
                    sb.AppendLine("        if (row < 1) row = 1;");
                    sb.AppendLine("        if (col < 1) col = 1;");
                    sb.AppendLine("        destination[0] = '\\x1b';");
                    sb.AppendLine("        destination[1] = '[';");
                    sb.AppendLine("        int n = AppendI32(destination, 2, row);");
                    sb.AppendLine("        destination[n++] = ';';");
                    sb.AppendLine("        n = AppendI32(destination, n, col);");
                    sb.AppendLine("        destination[n++] = 'H';");
                    sb.AppendLine("        return n;");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                if (emitted.Add("Position"))
                {
                    sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatPosition\"/>.</summary>");
                    sb.AppendLine("    public static string Position(int row, int col)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        Span<char> buf = stackalloc char[CsiFormatLength + 1];");
                    sb.AppendLine("        int n = FormatPosition(row, col, buf);");
                    sb.AppendLine("        return new string(buf[..n]);");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                break;

            case "StyleFlag":
                if (emitted.Add("StyleFormatLength"))
                {
                    sb.AppendLine("    /// <summary>Max chars written by <see cref=\"FormatStyle\"/> (params + separators).</summary>");
                    sb.AppendLine("    public const int StyleFormatLength = 11;");
                    sb.AppendLine();
                }
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    ///     Writes the SGR decoration params (e.g. <c>1;4</c>) for");
                sb.AppendLine("    ///     <paramref name=\"style\"/> into <paramref name=\"destination\"/>");
                sb.AppendLine("    ///     without allocation. Returns the written char count (0 for");
                sb.AppendLine("    ///     <see cref=\"StyleFlag.None\"/>), or -1 when the buffer is too small.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static int FormatStyle(StyleFlag style, Span<char> destination)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (destination.Length < StyleFormatLength) return -1;");
                sb.AppendLine("        int n = 0;");
                foreach (var m in members)
                {
                    if (m == "None") continue;
                    var code = StyleCode(m);
                    sb.AppendLine($"        if ((style & StyleFlag.{m}) != 0)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            if (n > 0) destination[n++] = ';';");
                    sb.AppendLine($"            destination[n++] = '{code}';");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                sb.AppendLine("        return n;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Allocating convenience wrapper for <see cref=\"FormatStyle\"/>.</summary>");
                sb.AppendLine("    public static string Style(StyleFlag style)");
                sb.AppendLine("    {");
                sb.AppendLine("        Span<char> buf = stackalloc char[StyleFormatLength];");
                sb.AppendLine("        int n = FormatStyle(style, buf);");
                sb.AppendLine("        return n == 0 ? string.Empty : new string(buf[..n]);");
                sb.AppendLine("    }");
                sb.AppendLine();
                break;
        }
    }

    private static string ColorCode(string member, bool isForeground)
    {
        return member switch
        {
            "Black" => isForeground ? "30" : "40",
            "Red" => isForeground ? "31" : "41",
            "Green" => isForeground ? "32" : "42",
            "Yellow" => isForeground ? "33" : "43",
            "Blue" => isForeground ? "34" : "44",
            "Magenta" => isForeground ? "35" : "45",
            "Cyan" => isForeground ? "36" : "46",
            "White" => isForeground ? "37" : "47",
            "BrightBlack" => isForeground ? "90" : "100",
            "BrightRed" => isForeground ? "91" : "101",
            "BrightGreen" => isForeground ? "92" : "102",
            "BrightYellow" => isForeground ? "93" : "103",
            "BrightBlue" => isForeground ? "94" : "104",
            "BrightMagenta" => isForeground ? "95" : "105",
            "BrightCyan" => isForeground ? "96" : "106",
            "BrightWhite" => isForeground ? "97" : "107",
            _ => isForeground ? "39" : "49",
        };
    }

    private static string StyleCode(string member)
    {
        return member switch
        {
            "Bold" => "1",
            "Dim" => "2",
            "Italic" => "3",
            "Underline" => "4",
            "Strike" => "9",
            "Reverse" => "7",
            _ => "0",
        };
    }
}
