<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsRoslynComponentPackage>true</IsRoslynComponentPackage>
    <RoslynComponent>Harbor.CodeGen</RoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Harbor.Abstractions.Contracts\Harbor.Abstractions.Contracts.csproj"/>
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);RS1041;S1944</NoWarn>
  </PropertyGroup>

</Project>
