using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>Attribute to mark mood classes for frame-bank generation by MoodFrameGenerator.</summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class MoodFrameAttribute : Attribute
{
    /// <summary>Initializes a new instance of the MoodFrameAttribute class.</summary>
    public MoodFrameAttribute(params string[] moods)
    {
        Moods = moods;
    }

    /// <summary>Gets the mood names (e.g., "Idle", "Working", "Thinking").</summary>
    public string[] Moods { get; }
}

[Generator]
public sealed class MoodFrameGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var moodClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Harbor.CodeGen.MoodFrameAttribute",
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var allMoods = moodClasses.Collect();

        context.RegisterSourceOutput(allMoods, static (spc, symbols) =>
        {
            if (symbols.Length == 0) return;

            var ns = symbols[0].ContainingNamespace.ToDisplayString();
            var source = GenerateMoodFrames(ns, symbols);
            spc.AddSource($"MoodFrames_{ns.Replace('.', '_')}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateMoodFrames(string ns, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.MoodFrameGenerator from [MoodFrame].");
        sb.AppendLine("// Mood → frame-bank dispatch table — do not edit; banks live on AmbientMascot.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        var emitted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in symbols)
        {
            var moodClassName = symbol.Name;
            GenerateMoodDispatch(sb, moodClassName, emitted);
        }

        return sb.ToString();
    }

private static void GenerateMoodDispatch(StringBuilder sb, string moodClassName, HashSet<string> emitted)
        {
            var boundaryName = moodClassName + "Frames";

        if (!emitted.Add("Dispatch_" + moodClassName))
            return;

        sb.AppendLine("/// <summary>Generated dispatch table for <see cref=\"" + moodClassName + "\"/> mood frame banks.</summary>");
        sb.AppendLine("public static class " + boundaryName + "");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Frame bank for a mood — static arrays, never copied.</summary>");
        sb.AppendLine("    public static string[] FramesOf() => " + moodClassName + ".Frames;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Index into the mood's frame bank for the given monotonic tick.</summary>");
        sb.AppendLine("    public static int FrameIndex(long monotonicTick)");
        sb.AppendLine("    {");
        sb.AppendLine("        string[] frames = FramesOf();");
        sb.AppendLine("        long period = 1; // Deterministic; negative ticks wrap.");
        sb.AppendLine("        int i = (int)((monotonicTick / period) % frames.Length);");
        sb.AppendLine("        return i >= 0 ? i : i + frames.Length;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame for the given monotonic tick. Deterministic.</summary>");
        sb.AppendLine("    public static string Frame(long monotonicTick) => FramesOf()[FrameIndex(monotonicTick)];");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Number of frames in the mood's bank.</summary>");
        sb.AppendLine("    public static int FrameCount() => FramesOf().Length;");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}