<<<<<<< HEAD
using System.Collections.Immutable;
using System.Text;
=======
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Harbor.Abstractions.Contracts;
>>>>>>> sprint/codegen-boilerplate
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

<<<<<<< HEAD
/// <summary>Attribute to mark mood classes for frame-bank generation by MoodFrameGenerator.</summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class MoodFrameAttribute : Attribute
{
    /// <summary>Initializes a new instance of the MoodFrameAttribute class.</summary>
    public MoodFrameAttribute(params string[] moods)
    {
        Moods = moods;
    }

    /// <summary>Gets the mood names (e.g., "Idle", "Working", "Thinking").</summary>
    public string[] Moods { get; }
}

=======
/// <summary>
///     Incremental source generator for mood-frame dispatch tables.
///     Scans for enums whose members carry <see cref="MoodFrameAttribute" />
///     and emits a static dispatch class replacing the manual switch
///     expression in the host class (e.g. <see cref="AmbientMascot.FramesOf"/>).
/// </summary>
>>>>>>> sprint/codegen-boilerplate
[Generator]
public sealed class MoodFrameGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
<<<<<<< HEAD
        var moodClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Harbor.CodeGen.MoodFrameAttribute",
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var allMoods = moodClasses.Collect();

        context.RegisterSourceOutput(allMoods, static (spc, symbols) =>
        {
            if (symbols.Length == 0) return;

            var ns = symbols[0].ContainingNamespace.ToDisplayString();
            var source = GenerateMoodFrames(ns, symbols);
            spc.AddSource($"MoodFrames_{ns.Replace('.', '_')}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateMoodFrames(string ns, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.MoodFrameGenerator from [MoodFrame].");
        sb.AppendLine("// Mood → frame-bank dispatch table — do not edit; banks live on AmbientMascot.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        var emitted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in symbols)
        {
            var moodClassName = symbol.Name;
            GenerateMoodDispatch(sb, moodClassName, emitted);
        }

        return sb.ToString();
    }

private static void GenerateMoodDispatch(StringBuilder sb, string moodClassName, HashSet<string> emitted)
        {
            var boundaryName = moodClassName + "Frames";

        if (!emitted.Add("Dispatch_" + moodClassName))
            return;

        sb.AppendLine("/// <summary>Generated dispatch table for <see cref=\"" + moodClassName + "\"/> mood frame banks.</summary>");
        sb.AppendLine("public static class " + boundaryName + "");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Frame bank for a mood — static arrays, never copied.</summary>");
        sb.AppendLine("    public static string[] FramesOf() => " + moodClassName + ".Frames;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Index into the mood's frame bank for the given monotonic tick.</summary>");
        sb.AppendLine("    public static int FrameIndex(long monotonicTick)");
        sb.AppendLine("    {");
        sb.AppendLine("        string[] frames = FramesOf();");
        sb.AppendLine("        long period = 1; // Deterministic; negative ticks wrap.");
        sb.AppendLine("        int i = (int)((monotonicTick / period) % frames.Length);");
        sb.AppendLine("        return i >= 0 ? i : i + frames.Length;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame for the given monotonic tick. Deterministic.</summary>");
        sb.AppendLine("    public static string Frame(long monotonicTick) => FramesOf()[FrameIndex(monotonicTick)];");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Number of frames in the mood's bank.</summary>");
        sb.AppendLine("    public static int FrameCount() => FramesOf().Length;");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}
=======
        var allMoodMembers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.EnumMemberDeclarationSyntax,
                transform: static (ctx, _) => (IFieldSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!)
            .Where(static m => m.GetAttributes().Any(ad => ad.AttributeClass?.Name == nameof(MoodFrameAttribute)))
            .Collect();

        context.RegisterSourceOutput(allMoodMembers, static (spc, members) =>
        {
            var grouped = members
                .Select(m =>
                {
                    var enumSymbol = m.ContainingType;
                    var enumName = enumSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                    var @namespace = enumSymbol.ContainingNamespace.ToDisplayString();

                    var attrData = m.GetAttributes()
                        .FirstOrDefault(ad => ad.AttributeClass?.Name == nameof(MoodFrameAttribute));
                    string frameBank = string.Empty;
                    string? panelEars = null;
                    string? panelPaws = null;

                    if (attrData is not null)
                    {
                        if (attrData.ConstructorArguments.Length > 0)
                        {
                            frameBank = attrData.ConstructorArguments[0].Value?.ToString() ?? string.Empty;
                        }
                        foreach (var na in attrData.NamedArguments)
                        {
                            switch (na.Key)
                            {
                                case nameof(MoodFrameAttribute.PanelEars):
                                    panelEars = na.Value.Value?.ToString();
                                    break;
                                case nameof(MoodFrameAttribute.PanelPaws):
                                    panelPaws = na.Value.Value?.ToString();
                                    break;
                            }
                        }
                    }

                    return (
                        EnumName: enumName,
                        Namespace: @namespace,
                        MemberName: m.Name,
                        FrameBank: frameBank,
                        PanelEars: panelEars,
                        PanelPaws: panelPaws
                    );
                })
                .GroupBy(x => (x.EnumName, x.Namespace))
                .Select(g => g.ToArray())
                .ToArray();

            foreach (var data in grouped)
            {
                spc.AddSource($"MoodFrameDispatch_{Sanitize(data[0].EnumName)}.g.cs", SourceText.From(GenerateDispatch(data), Encoding.UTF8));
            }
        });
    }

    private static string Sanitize(string s) => s.Replace('.', '_').Replace('+', '_');

    private static string GenerateDispatch((string EnumName, string Namespace, string MemberName, string FrameBank, string? PanelEars, string? PanelPaws)[] data)
    {
        var first = data[0];
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// MoodFrameGenerator — DO NOT EDIT");
        sb.AppendLine($"namespace {first.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated mood-frame dispatch table.</summary>");
        sb.AppendLine($"public static class {first.EnumName}FrameDispatch");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Frame bank for the given <see cref=\"{first.EnumName}\" />.</summary>");
        sb.AppendLine($"    public static string[] FramesOf({first.EnumName} mood) => mood switch");
        sb.AppendLine("    {");

        var defaultMember = data.FirstOrDefault(d => d.MemberName.Contains("Idle"));
        string defaultFrameBank = !string.IsNullOrEmpty(defaultMember.FrameBank) ? defaultMember.FrameBank : "Array.Empty<string>()";
        foreach (var d in data.OrderBy(d => d.MemberName))
        {
            sb.AppendLine($"        {first.EnumName}.{d.MemberName} => {d.FrameBank},");
        }
        sb.AppendLine($"        _ => {defaultFrameBank},");
        sb.AppendLine("    };");

        bool hasEars = data.Any(d => !string.IsNullOrEmpty(d.PanelEars));
        bool hasPaws = data.Any(d => !string.IsNullOrEmpty(d.PanelPaws));

        if (hasEars)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Panel ear row for the given mood.</summary>");
            sb.AppendLine($"    public static string[] PanelEarsOf({first.EnumName} mood) => mood switch");
            sb.AppendLine("    {");
            foreach (var d in data.Where(d => !string.IsNullOrEmpty(d.PanelEars)).OrderBy(d => d.MemberName))
            {
                sb.AppendLine($"        {first.EnumName}.{d.MemberName} => {d.PanelEars},");
            }
            string defaultEars = data.FirstOrDefault(d => !string.IsNullOrEmpty(d.PanelEars)) is { } de ? de.PanelEars! : "Array.Empty<string>()";
            sb.AppendLine($"        _ => {defaultEars},");
            sb.AppendLine("    };");
        }

        if (hasPaws)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Panel paw row for the given mood.</summary>");
            sb.AppendLine($"    public static string[] PanelPawsOf({first.EnumName} mood) => mood switch");
            sb.AppendLine("    {");
            foreach (var d in data.Where(d => !string.IsNullOrEmpty(d.PanelPaws)).OrderBy(d => d.MemberName))
            {
                sb.AppendLine($"        {first.EnumName}.{d.MemberName} => {d.PanelPaws},");
            }
            string defaultPaws = data.FirstOrDefault(d => !string.IsNullOrEmpty(d.PanelPaws)) is { } dp ? dp.PanelPaws! : "Array.Empty<string>()";
            sb.AppendLine($"        _ => {defaultPaws},");
            sb.AppendLine("    };");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
>>>>>>> sprint/codegen-boilerplate
