using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Harbor.Abstractions.Contracts;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>
///     Incremental source generator for mood-frame dispatch tables.
///     Scans for enums whose members carry <see cref="MoodFrameAttribute" />
///     and emits a static dispatch class replacing the manual switch
///     expression in the host class (e.g. <see cref="AmbientMascot.FramesOf"/>).
/// </summary>
[Generator]
public sealed class MoodFrameGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allMoodMembers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.EnumMemberDeclarationSyntax,
                transform: static (ctx, _) => (IFieldSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!)
            .Where(static m => m.GetAttributes().Any(ad => ad.AttributeClass?.Name == nameof(MoodFrameAttribute)))
            .Collect();

        context.RegisterSourceOutput(allMoodMembers, static (spc, members) =>
        {
            var grouped = members
                .Select(m =>
                {
                    var enumSymbol = m.ContainingType;
                    var enumName = enumSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                    var @namespace = enumSymbol.ContainingNamespace.ToDisplayString();

                    var attrData = m.GetAttributes()
                        .FirstOrDefault(ad => ad.AttributeClass?.Name == nameof(MoodFrameAttribute));
                    string frameBank = string.Empty;
                    string? panelEars = null;
                    string? panelPaws = null;

                    if (attrData is not null)
                    {
                        if (attrData.ConstructorArguments.Length > 0)
                        {
                            frameBank = attrData.ConstructorArguments[0].Value?.ToString() ?? string.Empty;
                        }
                        foreach (var na in attrData.NamedArguments)
                        {
                            switch (na.Key)
                            {
                                case nameof(MoodFrameAttribute.PanelEars):
                                    panelEars = na.Value.Value?.ToString();
                                    break;
                                case nameof(MoodFrameAttribute.PanelPaws):
                                    panelPaws = na.Value.Value?.ToString();
                                    break;
                            }
                        }
                    }

                    return (
                        EnumName: enumName,
                        Namespace: @namespace,
                        MemberName: m.Name,
                        FrameBank: frameBank,
                        PanelEars: panelEars,
                        PanelPaws: panelPaws
                    );
                })
                .GroupBy(x => (x.EnumName, x.Namespace))
                .Select(g => g.ToArray())
                .ToArray();

            foreach (var data in grouped)
            {
                spc.AddSource($"MoodFrameDispatch_{Sanitize(data[0].EnumName)}.g.cs", SourceText.From(GenerateDispatch(data), Encoding.UTF8));
            }
        });
    }

    private static string Sanitize(string s) => s.Replace('.', '_').Replace('+', '_');

    private static string GenerateDispatch((string EnumName, string Namespace, string MemberName, string FrameBank, string? PanelEars, string? PanelPaws)[] data)
    {
        var first = data[0];
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// MoodFrameGenerator — DO NOT EDIT");
        sb.AppendLine($"namespace {first.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated mood-frame dispatch table.</summary>");
        sb.AppendLine($"public static class {first.EnumName}FrameDispatch");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Frame bank for the given <see cref=\"{first.EnumName}\" />.</summary>");
        sb.AppendLine($"    public static string[] FramesOf({first.EnumName} mood) => mood switch");
        sb.AppendLine("    {");

        var defaultMember = data.FirstOrDefault(d => d.MemberName.Contains("Idle"));
        string defaultFrameBank = !string.IsNullOrEmpty(defaultMember.FrameBank) ? defaultMember.FrameBank : "Array.Empty<string>()";
        foreach (var d in data.OrderBy(d => d.MemberName))
        {
            sb.AppendLine($"        {first.EnumName}.{d.MemberName} => {d.FrameBank},");
        }
        sb.AppendLine($"        _ => {defaultFrameBank},");
        sb.AppendLine("    };");

        bool hasEars = data.Any(d => !string.IsNullOrEmpty(d.PanelEars));
        bool hasPaws = data.Any(d => !string.IsNullOrEmpty(d.PanelPaws));

        if (hasEars)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Panel ear row for the given mood.</summary>");
            sb.AppendLine($"    public static string[] PanelEarsOf({first.EnumName} mood) => mood switch");
            sb.AppendLine("    {");
            foreach (var d in data.Where(d => !string.IsNullOrEmpty(d.PanelEars)).OrderBy(d => d.MemberName))
            {
                sb.AppendLine($"        {first.EnumName}.{d.MemberName} => {d.PanelEars},");
            }
            string defaultEars = data.FirstOrDefault(d => !string.IsNullOrEmpty(d.PanelEars)) is { } de ? de.PanelEars! : "Array.Empty<string>()";
            sb.AppendLine($"        _ => {defaultEars},");
            sb.AppendLine("    };");
        }

        if (hasPaws)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Panel paw row for the given mood.</summary>");
            sb.AppendLine($"    public static string[] PanelPawsOf({first.EnumName} mood) => mood switch");
            sb.AppendLine("    {");
            foreach (var d in data.Where(d => !string.IsNullOrEmpty(d.PanelPaws)).OrderBy(d => d.MemberName))
            {
                sb.AppendLine($"        {first.EnumName}.{d.MemberName} => {d.PanelPaws},");
            }
            string defaultPaws = data.FirstOrDefault(d => !string.IsNullOrEmpty(d.PanelPaws)) is { } dp ? dp.PanelPaws! : "Array.Empty<string>()";
            sb.AppendLine($"        _ => {defaultPaws},");
            sb.AppendLine("    };");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
