using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>Attribute to mark renderer classes for adapter generation by RendererAdapterGenerator.</summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class TuiRendererAttribute : Attribute
{
    /// <summary>Initializes a new instance of the TuiRendererAttribute class.</summary>
    public TuiRendererAttribute(string backend)
    {
        Backend = backend;
    }

    /// <summary>Gets the backend name (e.g., "ansi", "plain", "cellforge", "nickconsoleex").</summary>
    public string Backend { get; }
}

[Generator]
public sealed class RendererAdapterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rendererClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Harbor.CodeGen.TuiRendererAttribute",
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        var allRenderers = rendererClasses.Collect();

        context.RegisterSourceOutput(allRenderers, static (spc, symbols) =>
        {
            if (symbols.Length == 0) return;

            var ns = symbols[0].ContainingNamespace.ToDisplayString();
            var source = GenerateRendererAdapters(ns, symbols);
            spc.AddSource($"TuiRendererAdapter_{ns.Replace('.', '_')}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateRendererAdapters(string ns, ImmutableArray<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.RendererAdapterGenerator from [TuiRenderer].");
        sb.AppendLine("// Zero-allocation frame adapters — do not edit; hand-written logic belongs in the renderer.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        var emitted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in symbols)
        {
            var rendererName = symbol.Name;
            var backend = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "TuiRendererAttribute")
                ?.ConstructorArguments
                .FirstOrDefault()
                .Value as string ?? "unknown";

            GenerateAdapter(sb, rendererName, backend, emitted);
            GenerateFrameBoundaries(sb, rendererName, backend, emitted);
        }

        return sb.ToString();
    }

    private static void GenerateAdapter(StringBuilder sb, string rendererName, string backend, HashSet<string> emitted)
    {
        var className = rendererName.EndsWith("TuiRenderer") ? rendererName : rendererName + "TuiRenderer";

        if (!emitted.Add("Adapter_" + rendererName))
            return;

        sb.AppendLine("/// <summary>Generated backend adapter for the '" + backend + "' renderer backend.</summary>");
        sb.AppendLine("public partial class " + className + "");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Stable backend id from [TuiRenderer].</summary>");
        sb.AppendLine("    public const string BackendId = \"" + backend + "\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Whether the backend owns the terminal cursor across a frame.</summary>");
        sb.AppendLine("    public const bool CursorFrameBoundary = true;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame prologue — hides the cursor when the backend owns it across frames.</summary>");
        sb.AppendLine("    public static void WriteFramePrologue(global::System.IO.TextWriter writer)");
        sb.AppendLine("    {");
        GenerateFramePrologue(sb, backend);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame epilogue — shows the cursor when the backend owns it across frames.</summary>");
        sb.AppendLine("    public static void WriteFrameEpilogue(global::System.IO.TextWriter writer)");
        sb.AppendLine("    {");
        GenerateFrameEpilogue(sb, backend);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateFramePrologue(StringBuilder sb, string backend)
    {
        switch (backend)
        {
            case "ansi":
                sb.AppendLine("        writer.Write(\"\\x1b[?25l\");");
                break;
            case "plain":
                sb.AppendLine("        // Plain backend does not own cursor across frames");
                sb.AppendLine("        writer.Write(string.Empty);");
                break;
            case "cellforge":
                sb.AppendLine("        writer.Write(\"\\x1b[?25l\");");
                break;
            case "nickconsoleex":
                sb.AppendLine("        writer.Write(\"\\x1b[?25l\");");
                break;
            default:
                sb.AppendLine("        writer.Write(string.Empty);");
                break;
        }
    }

    private static void GenerateFrameEpilogue(StringBuilder sb, string backend)
    {
        switch (backend)
        {
            case "ansi":
                sb.AppendLine("        writer.Write(\"\\x1b[?25h\");");
                break;
            case "plain":
                sb.AppendLine("        // Plain backend does not own cursor across frames");
                sb.AppendLine("        writer.Write(string.Empty);");
                break;
            case "cellforge":
                sb.AppendLine("        writer.Write(\"\\x1b[?25h\");");
                break;
            case "nickconsoleex":
                sb.AppendLine("        writer.Write(\"\\x1b[?25h\");");
                break;
            default:
                sb.AppendLine("        writer.Write(string.Empty);");
                break;
        }
    }

    private static void GenerateFrameBoundaries(StringBuilder sb, string rendererName, string backend, HashSet<string> emitted)
    {
        var className = rendererName.EndsWith("TuiRenderer") ? rendererName : rendererName + "TuiRenderer";
        var boundaryName = className + "FrameBoundaries";

        if (!emitted.Add(boundaryName))
            return;

        sb.AppendLine("/// <summary>Frame boundary detection for the '" + backend + "' renderer backend.</summary>");
        sb.AppendLine("public static class " + boundaryName + "");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Whether a frame boundary occurs at the given position.</summary>");
        sb.AppendLine("    public static bool IsFrameBoundary(global::System.IO.TextWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine("        return " + className + ".CursorFrameBoundary && writer is System.IO.StringWriter;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}