using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Harbor.Abstractions.Contracts;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>
///     Incremental source generator for TUI renderer adapters.
///     Scans for classes annotated with <see cref="TuiRendererAttribute" />
///     and emits a partial class with backend metadata (id, frame-boundary
///     constants) plus a static adapter helper the host frame loop can use
///     to specialise output per backend.
/// </summary>
[Generator]
public sealed class RendererAdapterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!)
            .Select(static (classSymbol, _) =>
            {
                var className = classSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var @namespace = classSymbol.ContainingNamespace.ToDisplayString();

                var attrData = classSymbol.GetAttributes()
                    .FirstOrDefault(ad => ad.AttributeClass?.Name == nameof(TuiRendererAttribute));
                string backend = string.Empty;
                string? contextType = null;
                string? argsFormatter = null;

                if (attrData is not null)
                {
                    foreach (var na in attrData.NamedArguments)
                    {
                        switch (na.Key)
                        {
                            case nameof(TuiRendererAttribute.Backend):
                                backend = na.Value.Value?.ToString() ?? string.Empty;
                                break;
                            case nameof(TuiRendererAttribute.ContextType):
                                contextType = na.Value.Value?.ToString();
                                break;
                            case nameof(TuiRendererAttribute.ArgsFormatter):
                                argsFormatter = na.Value.Value?.ToString();
                                break;
                        }
                    }
                }

                return (
                    ClassName: className,
                    Namespace: @namespace,
                    Backend: backend,
                    ContextType: contextType,
                    ArgsFormatter: argsFormatter
                );
            })
            .Where(static data => !string.IsNullOrEmpty(data.Backend));

        context.RegisterSourceOutput(classSymbols, static (spc, data) =>
        {
            spc.AddSource($"TuiRendererAdapter_{Sanitize(data.ClassName)}.g.cs", SourceText.From(GenerateAdapter(data), Encoding.UTF8));
        });
    }

    private static string Sanitize(string s) => s.Replace('.', '_').Replace('+', '_');

    private static string GenerateAdapter((string ClassName, string Namespace, string Backend, string? ContextType, string? ArgsFormatter) data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// RendererAdapterGenerator — DO NOT EDIT");
        sb.AppendLine($"namespace {data.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated backend adapter metadata.</summary>");
        sb.AppendLine($"public static class {data.ClassName}Adapter");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Stable backend id from [TuiRenderer].</summary>");
        sb.AppendLine($"    public const string BackendId = \"{data.Backend}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Whether the backend owns the terminal cursor across a frame.</summary>");
        string backendLower = data.Backend.ToLowerInvariant();
        bool ownsCursor = backendLower != "plain" && backendLower != "nickconsoleex";
        sb.AppendLine($"    public const bool CursorFrameBoundary = {ownsCursor.ToString().ToLowerInvariant()};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame prologue — hides the cursor when the backend owns it across frames.</summary>");
        sb.AppendLine("    public static void WriteFramePrologue(System.IO.TextWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        writer.Write({(ownsCursor ? "\"\\x1b[?25l\"" : "string.Empty")});");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame epilogue — shows the cursor when the backend owns it across frames.</summary>");
        sb.AppendLine("    public static void WriteFrameEpilogue(System.IO.TextWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        writer.Write({(ownsCursor ? "\"\\x1b[?25h\"" : "string.Empty")});");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Whether a frame boundary occurs at the given writer.</summary>");
        sb.AppendLine("    public static bool IsFrameBoundary(System.IO.TextWriter writer)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return CursorFrameBoundary && writer is System.IO.StringWriter;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
