using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

/// <summary>
///     Generates frame-boundary adapters for TUI renderer backends annotated
///     with <c>[TuiRenderer]</c>.
/// </summary>
/// <remarks>
///     <para>
///         For every annotated class the generator emits a partial-class
///         companion carrying the <c>BackendId</c> constant, the
///         <c>CursorFrameBoundary</c> flag and zero-alloc frame prologue /
///         epilogue writers (hide / show cursor when the backend owns the
///         terminal cursor across a frame). Per namespace it additionally
///         emits a <c>TuiRendererFrameBoundaries</c> lookup table mapping
///         backend ids to their boundary flag; unknown ids return
///         <c>false</c> (no boundary).
///     </para>
///     <para>
///         Opt-in per backend: backends without the attribute get nothing.
///     </para>
/// </remarks>
[Generator]
public sealed class RendererAdapterGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Harbor.CodeGen.TuiRendererAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var backends = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => RendererBackendInfo.Create((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(backends.Collect(), static (spc, list) => Emit(spc, list));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<RendererBackendInfo> backends)
    {
        if (backends.IsEmpty)
        {
            return;
        }

        foreach (var backend in backends)
        {
            spc.AddSource(
                $"TuiRendererAdapter_{Sanitize(backend.Namespace)}_{backend.ClassName}.g.cs",
                SourceText.From(EmitAdapter(backend), Encoding.UTF8));
        }
        foreach (var group in backends.GroupBy(static b => b.Namespace))
        {
            spc.AddSource(
                $"TuiRendererFrameBoundaries_{Sanitize(group.Key)}.g.cs",
                SourceText.From(EmitBoundaryTable(group.ToList()), Encoding.UTF8));
        }
    }

    private static string EmitAdapter(RendererBackendInfo backend)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.RendererAdapterGenerator from [TuiRenderer].");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {backend.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Generated backend adapter for the '{backend.Backend}' renderer backend.</summary>");
        sb.AppendLine($"{backend.Accessibility}{(backend.IsSealed ? " sealed" : string.Empty)} partial class {backend.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Stable backend id from [TuiRenderer].</summary>");
        sb.AppendLine($"    public const string BackendId = \"{backend.Backend}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Whether the backend owns the terminal cursor across a frame.</summary>");
        sb.AppendLine($"    public const bool CursorFrameBoundary = {(backend.CursorBoundary ? "true" : "false")};");
        sb.AppendLine();

        // The guard is specialized at generation time: with a literal false
        // boundary a runtime `if` would produce unreachable code (CS0162
        // under TreatWarningsAsErrors), so no-op bodies are emitted instead.
        sb.AppendLine("    /// <summary>Frame prologue — hides the cursor when the backend owns it across frames.</summary>");
        sb.AppendLine("    public static void WriteFramePrologue(global::System.IO.TextWriter writer)");
        if (backend.CursorBoundary)
        {
            EmitCursorWrite(sb, "\\x1b[?25l");
        }
        else
        {
            sb.AppendLine("    {");
            sb.AppendLine("        // No cursor ownership — the frame boundary is a no-op.");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Frame epilogue — shows the cursor when the backend owns it across frames.</summary>");
        sb.AppendLine("    public static void WriteFrameEpilogue(global::System.IO.TextWriter writer)");
        if (backend.CursorBoundary)
        {
            EmitCursorWrite(sb, "\\x1b[?25h");
        }
        else
        {
            sb.AppendLine("    {");
            sb.AppendLine("        // No cursor ownership — the frame boundary is a no-op.");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitCursorWrite(StringBuilder sb, string sequence)
    {
        sb.AppendLine("    {");
        sb.AppendLine($"        writer.Write(\"{sequence}\");");
        sb.AppendLine("    }");
    }

    private static string EmitBoundaryTable(IReadOnlyList<RendererBackendInfo> group)
    {
        var backends = group.ToList();
        string ns = backends[0].Namespace;
        // One table per namespace: keep the source order stable so the
        // generated switch is deterministic across incremental runs.
        backends.Sort(static (a, b) => string.CompareOrdinal(a.ClassName, b.ClassName));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Harbor.CodeGen.RendererAdapterGenerator from [TuiRenderer].");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated backend-id → frame-boundary table (source: [TuiRenderer]).</summary>");
        sb.AppendLine("public static class TuiRendererFrameBoundaries");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Whether the backend with the given id owns the cursor across frames; unknown ids → false.</summary>");
        sb.AppendLine("    public static bool HasCursorFrameBoundary(string backendId) => backendId switch");
        sb.AppendLine("    {");
        foreach (var backend in backends)
        {
            sb.AppendLine($"        {backend.ClassName}.BackendId => {(backend.CursorBoundary ? "true" : "false")},");
        }

        sb.AppendLine("        _ => false,");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Sanitize(string ns)
    {
        var sb = new StringBuilder(ns.Length);
        foreach (var c in ns)
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return sb.ToString();
    }
}

/// <summary>Equatable snapshot of a [TuiRenderer] class for the incremental pipeline.</summary>
internal sealed class RendererBackendInfo : IEquatable<RendererBackendInfo>
{
    public RendererBackendInfo(
        string className,
        string ns,
        string accessibility,
        bool isSealed,
        string backend,
        bool cursorBoundary)
    {
        ClassName = className;
        Namespace = ns;
        Accessibility = accessibility;
        IsSealed = isSealed;
        Backend = backend;
        CursorBoundary = cursorBoundary;
    }

    public string ClassName { get; }

    public string Namespace { get; }

    public string Accessibility { get; }

    public bool IsSealed { get; }

    public string Backend { get; }

    public bool CursorBoundary { get; }

    public bool Equals(RendererBackendInfo? other) =>
        other is not null
        && ClassName == other.ClassName
        && Namespace == other.Namespace
        && Accessibility == other.Accessibility
        && IsSealed == other.IsSealed
        && Backend == other.Backend
        && CursorBoundary == other.CursorBoundary;

    public override bool Equals(object? obj) => Equals(obj as RendererBackendInfo);

    public override int GetHashCode()
    {
        unchecked
        {
            int hash = ClassName.GetHashCode() * 397;
            hash ^= Namespace.GetHashCode();
            hash ^= Backend.GetHashCode();
            hash ^= CursorBoundary.GetHashCode();
            return hash;
        }
    }

    public static RendererBackendInfo Create(INamedTypeSymbol classSymbol)
    {
        AttributeData? attr = null;
        foreach (var candidate in classSymbol.GetAttributes())
        {
            if (candidate.AttributeClass?.MetadataName == "TuiRendererAttribute")
            {
                attr = candidate;
                break;
            }
        }

        string backend = attr is not null
            && attr.ConstructorArguments.Length > 0
            && attr.ConstructorArguments[0].Value is string id
            ? id
            : string.Empty;

        bool cursor = false;
        if (attr is not null)
        {
            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "CursorFrameBoundary" && named.Value.Value is bool flag)
                {
                    cursor = flag;
                }
            }
        }

        string accessibility = classSymbol.DeclaredAccessibility switch
        {
            Microsoft.CodeAnalysis.Accessibility.Public => "public",
            Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
            Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
            Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal",
        };

        return new RendererBackendInfo(
            classSymbol.Name,
            classSymbol.ContainingNamespace.ToDisplayString(),
            accessibility,
            classSymbol.IsSealed,
            backend,
            cursor);
    }
}
