using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Harbor.CodeGen;

[Generator]
public sealed class ResourceKeyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var themeFiles = context.AdditionalTextsProvider
            .Where(static (file) =>
                file.Path.Contains("Themes/Hds/", StringComparison.OrdinalIgnoreCase)
                && file.Path.EndsWith(".axaml", StringComparison.OrdinalIgnoreCase));

        var keys = themeFiles.Select(static (file, ct) =>
        {
            var result = new List<string>();
            try
            {
                using var reader = XmlReader.Create(file.Path, new XmlReaderSettings { DtdProcessing = DtdProcessing.Ignore });
                while (reader.Read())
                {
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        string? key = reader.GetAttribute("x:Key") ?? reader.GetAttribute("Key");
                        if (!string.IsNullOrEmpty(key))
                        {
                            result.Add(key);
                        }
                    }
                }
            }
            catch
            {
                // Malformed XAML is non-critical; skip bad files silently.
            }
            return result.ToArray();
        });

        context.RegisterImplementationSourceOutput(keys, (spc, k) =>
        {
            string[] distinct = k.Distinct().OrderBy(x => x).ToArray();
            if (distinct.Length == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Resource key constants generated from Themes/Hds/*.axaml");
            sb.AppendLine("namespace Harbor.App.Avalonia.Generated;");
            sb.AppendLine("public static class R");
            sb.AppendLine("{");

            foreach (string key in distinct)
            {
                var constName = MakeConstName(key);
                sb.Append("    internal const string ");
                sb.Append(constName);
                sb.Append(" = \"");
                sb.Append(key);
                sb.AppendLine("\";");
            }

            sb.AppendLine("}");

            spc.AddSource("ResourceKeys.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static string MakeConstName(string key)
    {
        var sb = new StringBuilder();
        foreach (var c in key)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
            else if (c == '_' || c == '-')
            {
                sb.Append('_');
            }
            else if (sb.Length > 0 && sb[sb.Length - 1] != '_')
            {
                sb.Append('_');
            }
        }
        return sb.ToString();
    }
}
