// DemoGifTriggerSurfaceTests.cs — #427: the demo GIFs are regenerated by a
// workflow that fires on `push` PATHS, so the A/B question "did anything that can
// move a pixel change?" is answered entirely by whether a recording input is
// inside that filter. docs/DEMO_GIFS.md teaches a maintainer to tell the two
// cases apart —
//
//   case A: the rendering code changed, so the GIF MUST move, and a red drift
//           gate is the correct signal;
//   case B: only the GIF moved, so nothing could have moved it — a foreign edit;
//
// — and case B is indistinguishable from case A unless the trigger surface is
// complete. That is what this file pins: if a recording input is not covered by
// `on.push.paths`, then a case-A change lands with NO workflow run, NO drift
// gate, NO red job — and the README GIFs are silently stale. Case A degrades
// into case B in total silence, which is worse than either case alone.
//
// It is deliberately NOT a guard about the GIF bytes themselves. It reads no GIF,
// computes no hash and needs no git history: CI checks out with depth 1, so
// "which files did this PR change relative to its base" is not answerable from a
// TUnit process, and a guard that claimed to answer it would be theatre. See the
// KNOWN LIMITATIONS block at the bottom.
//
// WHY THE DOCS GATE CANNOT DO THIS
// ---------------------------------
// ci.yml ignores `**.md` and `docs/**` on purpose, and docs.yml checks links,
// anchors, encoding, headings and fence balance — never whether a stated fact is
// still true. So DEMO_GIFS.md documenting the trigger surface creates no
// obligation for the trigger surface to stay correct; this file is that
// obligation.
//
// NON-VACUITY
// -----------
// A guard that matches nothing is indistinguishable from a broken one, and a
// broken guard is worse than no guard because it is believed. Three mechanisms:
//   1. `TheRecordingInputInventory_IsWhatWeThinkItIs` pins the inventory itself —
//      four tapes, run-scene.sh, install-toolchain.sh, toolchain.lock and the
//      pacer — so a rename that empties the scan is red, not "nothing uncovered".
//   2. `TheRule_FiresOnThePreFixTriggerList` replays the exact filter this file
//      was written against and requires all four uncovered inputs to be reported,
//      so the green rule above means "the matcher fired and found nothing".
//   3. `ThePushFilter_WasActuallyParsed` requires the parse to yield several
//      paths, so a parser that stops matching YAML reports "fully covered"
//      vacuously rather than "uncovered".
//
// STATUS: never compiled locally. Local dotnet builds are forbidden in this
// repository (many concurrent agents on one box), so the first CI run is the
// first build. Treat the C# as unverified until then; the first build to touch it
// may find a genuine compile error, and that is the point of sending it rather
// than a defect to reason about locally.

using System.Text;
using System.Text.RegularExpressions;

namespace Harbor.Architecture.Tests;

/// <summary>
///     Every input that can change a recorded demo GIF must be inside the
///     <c>demo-gifs</c> workflow's <c>on.push.paths</c> filter.
/// </summary>
public sealed class DemoGifTriggerSurfaceTests
{
    /// <summary>The workflow under audit, repo-relative.</summary>
    private const string WorkflowPath = ".github/workflows/demo.yml";

    /// <summary>
    ///     Recording inputs that live outside <c>demo/</c>. Every entry must be
    ///     named by the trigger filter explicitly, because a directory-wide glob
    ///     cannot reach it.
    /// </summary>
    private static readonly string[] RecordingInputsOutsideDemoDir =
    [
        // The frame pacer. tools/demo_repro.py `normalize` decides the frame
        // count, the per-frame delays and therefore the duration — every number
        // the drift gate compares. A change here changes every GIF.
        "tools/demo_repro.py",
    ];

    /// <summary>
    ///     The filter this guard was written against, verbatim from demo.yml as of
    ///     #427. Replayed in <see cref="TheRule_FiresOnThePreFixTriggerList" /> so
    ///     the defect it exists for is still demonstrable.
    /// </summary>
    private static readonly string[] PreFixTriggerPaths =
    [
        "src/Harbor.Tui.**",
        "src/Harbor.Terminal.Abstractions/**",
        "apps/Harbor.App.Cli/**",
        "demo/*.tape",
        ".github/workflows/demo.yml",
    ];

    /// <summary>
    ///     The recording inputs that filter left uncovered. The control asserts
    ///     the COUNT and then each NAME — not the order, so this list does not
    ///     have to be kept sorted, and a reordering here cannot turn the control
    ///     red for a reason that has nothing to do with the rule.
    /// </summary>
    private static readonly string[] PreFixUncoveredInputs =
    [
        "demo/install-toolchain.sh",
        "demo/run-scene.sh",
        "demo/toolchain.lock",
        "tools/demo_repro.py",
    ];

    /// <summary>
    ///     The rule: a recorded GIF can only be refreshed when the workflow runs,
    ///     and the workflow only runs when a covered path changed.
    /// </summary>
    [Test]
    public async Task EveryRecordingInput_IsCoveredByTheWorkflowTrigger()
    {
        string root = RequireRepoRoot();
        IReadOnlyList<string> covered = ReadPushPaths(root);

        IReadOnlyList<string> uncovered = FindUncoveredInputs(root, covered);

        await Assert.That(uncovered).IsEmpty()
            .Because("these files are read by the demo-gifs job and each one can change the "
                + "recorded pixels, but none of them is matched by the workflow's on.push.paths "
                + "filter. A change to any of them therefore lands on dev with no workflow run, no "
                + "drift gate and no red job — the README GIFs go stale silently, which is case B "
                + "(a GIF that moved for no reason) arriving without case A ever being detected. "
                + "Uncovered: " + string.Join(" | ", uncovered)
                + " Fix the FILTER, not the guard: widen on.push.paths to cover the recording "
                + "inputs. Do not delete an input from this list to make it green — see "
                + "FindUncoveredInputs, which derives the list from the tree, not from here.");
    }

    /// <summary>
    ///     Non-vacuity: the inventory the rule judges must be the inventory we
    ///     think it is.
    /// </summary>
    /// <remarks>
    ///     <c>demo/</c> is enumerated from disk. If it were empty, or if the
    ///     tapes were renamed, <c>FindUncoveredInputs</c> would report nothing and
    ///     the rule above would pass on the strength of having read zero files —
    ///     the exact vacuity this file exists to prevent.
    /// </remarks>
    [Test]
    public async Task TheRecordingInputInventory_IsWhatWeThinkItIs()
    {
        string root = RequireRepoRoot();
        string demoDir = Path.Combine(root, "demo");

        await Assert.That(Directory.Exists(demoDir)).IsTrue()
            .Because("the demo directory is the recorder's input surface. If it was moved or "
                + "renamed, update RecordingInputsOutsideDemoDir and say so in the file header.");

        string[] present =
        [
            .. Directory.GetFiles(demoDir)
                .Select(p => Path.GetFileName(p) ?? string.Empty)
                .OrderBy(n => n, StringComparer.Ordinal)
        ];

        foreach (string tape in new[] { "hero", "markdown", "approval", "plain" })
        {
            await Assert.That(present.Contains($"{tape}.tape", StringComparer.Ordinal)).IsTrue()
                .Because($"demo/{tape}.tape is one of the four recordings the workflow captures. "
                    + "Found: " + string.Join(" | ", present.OrderBy(p => p, StringComparer.Ordinal)));
        }

        // Both non-tape inputs inside demo/ are named explicitly by the positive
        // control below; if either stops existing, that control's expectation has
        // to be updated deliberately rather than by an empty comparison.
        foreach (string input in new[] { "run-scene.sh", "install-toolchain.sh", "toolchain.lock" })
        {
            await Assert.That(File.Exists(Path.Combine(demoDir, input))).IsTrue()
                .Because("demo/" + input + " is read by the recording job. Its absence has to be a "
                    + "decision recorded here, not a silent shrink of the scanned set.");
        }

        foreach (string outside in RecordingInputsOutsideDemoDir)
        {
            await Assert.That(File.Exists(Path.Combine(root, outside))).IsTrue()
                .Because(outside + " is read by the drift gate / normalise step and is named here "
                    + "because no directory-wide glob can cover it. If it moved, update the list "
                    + "and the filter together.");
        }
    }

    /// <summary>
    ///     Non-vacuity: the positive control. Replays the pre-#427 filter and
    ///     requires every uncovered input to be reported.
    /// </summary>
    /// <remarks>
    ///     The real filter is (as of this commit) complete, so the rule above is
    ///     satisfied by an empty list. That is what a correct filter looks like —
    ///     and it is also what a blind matcher looks like. This test is the
    ///     difference: a green rule then means "the matcher fired and found
    ///     nothing", which is the only reading that carries information.
    /// </remarks>
    [Test]
    public async Task TheRule_FiresOnThePreFixTriggerList()
    {
        string root = RequireRepoRoot();

        IReadOnlyList<string> uncovered = FindUncoveredInputs(root, PreFixTriggerPaths);

        await Assert.That(uncovered.Count).IsEqualTo(PreFixUncoveredInputs.Length)
            .Because("the pre-#427 filter ('demo/*.tape' only) left four recording inputs unable "
                + "to schedule a re-record. If that count changed, either the glob translation or "
                + "the inventory changed, and one of the two assertions in this file is now "
                + "describing a rule that is no longer the one being run. Reported: "
                + string.Join(" | ", uncovered));

        foreach (string expected in PreFixUncoveredInputs)
        {
            await Assert.That(uncovered.Contains(expected, StringComparer.Ordinal)).IsTrue()
                .Because("'" + expected + "' cannot move pixels under the pre-fix filter, which is "
                    + "the defect this guard exists to keep fixed. Reported: "
                    + string.Join(" | ", uncovered));
        }
    }

    /// <summary>
    ///     Non-vacuity for the YAML parse itself: the filter has to have been
    ///     READ, not inferred.
    /// </summary>
    /// <remarks>
    ///     A parser that quietly returns zero paths would make every input look
    ///     uncovered (loud), but a parser that returns a wildcard or that falls
    ///     back to "no filter means everything triggers" would make every input
    ///     look covered (silent). This pins the parse to a real, non-trivial
    ///     list.
    /// </remarks>
    [Test]
    public async Task ThePushFilter_WasActuallyParsed()
    {
        IReadOnlyList<string> covered = ReadPushPaths(RequireRepoRoot());

        await Assert.That(covered.Count).IsGreaterThanOrEqualTo(3)
            .Because("the demo-gifs workflow's on.push.paths filter was expected to hold several "
                + "globs. Parsed: " + string.Join(" | ", covered) + " — a near-empty result means "
                + "ReadPushPaths stopped understanding the YAML, and every coverage assertion in "
                + "this file would then be reporting on a filter nobody has.");

        await Assert.That(covered.Any(p => p.StartsWith("src/", StringComparison.Ordinal))).IsTrue()
            .Because("the src/ renderer paths are the filter's original reason to exist; their "
                + "absence means the parse found a different 'paths:' block than the one under "
                + "'push:'. Parsed: " + string.Join(" | ", covered));
    }

    /// <summary>
    ///     The recorder stays the only writer of <c>assets/demo/</c>, and it never
    ///     resolves a lost race by overwriting.
    /// </summary>
    /// <remarks>
    ///     docs/DEMO_GIFS.md tells a maintainer that a commit touching
    ///     <c>assets/demo/*.gif</c> without touching a recording input is case B —
    ///     a foreign edit. That instruction is only usable if GIF-only commits are
    ///     otherwise attributable, which is what the fixed commit subject gives:
    ///     26 of the 38 commits that have ever touched <c>assets/demo/</c> carry
    ///     exactly this subject and were written by the workflow. The second half
    ///     pins the other half of the same decision — the recorder re-bases and
    ///     gives up loudly rather than force-pushing, which is why a conflict is a
    ///     red job a human resolves instead of a silently lost regeneration.
    /// </remarks>
    [Test]
    public async Task TheRecorder_CommitsItsOwnSubject_AndNeverForcePushes()
    {
        string text = File.ReadAllText(Path.Combine(RequireRepoRoot(), WorkflowPath));

        await Assert.That(text.Contains(
            "git commit -m \"chore(demo): regenerate README GIFs [skip ci]\"", StringComparison.Ordinal)).IsTrue()
            .Because("docs/DEMO_GIFS.md identifies a GIF-only commit as the recorder's by this "
                + "exact subject. If the subject changes, the doc's procedure and the history it "
                + "is read against both go stale — change them together.");

        await Assert.That(text.Contains(
            "git add assets/demo/*-compressed.gif assets/demo/baseline.json", StringComparison.Ordinal)).IsTrue()
            .Because("the recorder's output set is the whole of what it is allowed to commit. A "
                + "narrower pathspec would leave a regenerated file behind, and a broader one would "
                + "let it commit something outside assets/demo/. Both are silent.");

        foreach (string forbidden in new[] { "push --force", "push -f ", "push origin +" })
        {
            await Assert.That(text.Contains(forbidden, StringComparison.Ordinal)).IsFalse()
                .Because("'" + forbidden.Trim() + "' in demo.yml would mean the recorder can resolve "
                    + "a rebase conflict by discarding someone else's GIFs. The workflow's own "
                    + "comment says a red that means 'I could not save the output' is honest and a "
                    + "green that means 'I threw it away' is not; a force-push would reintroduce "
                    + "exactly that.");
        }
    }

    /// <summary>
    ///     Every recording input not matched by any glob in <paramref name="paths" />.
    /// </summary>
    /// <remarks>
    ///     The inventory is derived from the TREE — every file in <c>demo/</c> plus
    ///     <see cref="RecordingInputsOutsideDemoDir" /> — never from a list kept
    ///     beside this rule. A guard whose subject list can be edited to match its
    ///     own findings is a guard that can be made green by deleting the subject.
    /// </remarks>
    private static List<string> FindUncoveredInputs(string root, IReadOnlyList<string> paths)
    {
        var matchers = paths.Select(ToGlobFilter).ToArray();
        var uncovered = new List<string>();

        foreach (string input in EnumerateRecordingInputs(root))
        {
            if (!matchers.Any(m => m.IsMatch(input)))
            {
                uncovered.Add(input);
            }
        }

        // Ordinal so the failure message and the positive control's expectation
        // agree on order rather than on whatever the filesystem happened to hand back.
        return [.. uncovered.OrderBy(p => p, StringComparer.Ordinal)];
    }

    /// <summary>
    ///     The recorder's input surface, repo-relative and ordinal-sorted: every
    ///     file in <c>demo/</c>, plus the inputs that live elsewhere.
    /// </summary>
    private static List<string> EnumerateRecordingInputs(string root)
    {
        var inputs = new List<string>();
        string demoDir = Path.Combine(root, "demo");

        if (Directory.Exists(demoDir))
        {
            inputs.AddRange(Directory
                .GetFiles(demoDir, "*", SearchOption.AllDirectories)
                .Select(p => Path.GetRelativePath(root, p).Replace('\\', '/')));
        }

        foreach (string outside in RecordingInputsOutsideDemoDir)
        {
            inputs.Add(outside);
        }

        return [.. inputs.OrderBy(p => p, StringComparer.Ordinal)];
    }

    /// <summary>
    ///     Reads the <c>paths:</c> list under <c>on.push</c> in the workflow.
    /// </summary>
    /// <remarks>
    ///     Deliberately a line reader rather than a YAML parser: the project takes
    ///     no YAML dependency, and the shape being read is fixed and small — a
    ///     <c>push:</c> key, a <c>paths:</c> key under it, then a run of
    ///     <c>- "glob"</c> list items. It stops at the first line that is not a
    ///     list item, so a sibling block (the <c>workflow_dispatch</c> inputs, for
    ///     instance) cannot leak in. <c>ThePushFilter_WasActuallyParsed</c> is what
    ///     stops a change to that shape from being read as a clean result.
    /// </remarks>
    private static List<string> ReadPushPaths(string root)
    {
        string workflow = Path.Combine(root, WorkflowPath);
        string[] lines = File.ReadAllLines(workflow);

        int push = Array.FindIndex(lines, l => l.TrimEnd() == "push:");
        if (push < 0)
        {
            return [];
        }

        int paths = Array.FindIndex(lines, push, l => l.TrimEnd() == "paths:");
        if (paths < 0)
        {
            return [];
        }

        var found = new List<string>();
        for (int i = paths + 1; i < lines.Length; i++)
        {
            string trimmed = lines[i].Trim();
            if (!trimmed.StartsWith("- \"", StringComparison.Ordinal) || !trimmed.EndsWith('"'))
            {
                break;
            }

            found.Add(trimmed[3..^1]);
        }

        return found;
    }

    /// <summary>
    ///     Translates a GitHub Actions path filter glob into an anchored regex.
    /// </summary>
    /// <remarks>
    ///     <c>**</c> matches across <c>/</c>, <c>*</c> and <c>?</c> do not, and every
    ///     other character is literal. The trailing <c>!**</c> negation form is NOT
    ///     implemented, and no current filter entry uses it: a filter that grows
    ///     one would read as covering less than it does, which fails loud. The
    ///     regex is compiled and culture-invariant so the same file set is judged
    ///     on every runner locale.
    /// </remarks>
    private static Regex ToGlobFilter(string pattern)
    {
        var builder = new StringBuilder("^");

        for (int i = 0; i < pattern.Length; i++)
        {
            char c = pattern[i];
            switch (c)
            {
                case '*' when i + 1 < pattern.Length && pattern[i + 1] == '*':
                    builder.Append(".*");
                    i++;
                    break;
                case '*':
                    builder.Append("[^/]*");
                    break;
                case '?':
                    builder.Append("[^/]");
                    break;
                default:
                    builder.Append(Regex.Escape(c.ToString()));
                    break;
            }
        }

        return new Regex(builder.Append('$').ToString(),
            RegexOptions.CultureInvariant | RegexOptions.Compiled);
    }

    private static string RequireRepoRoot()
    {
        string? root = RepoPaths.RepoRoot;
        return root ?? throw new InvalidOperationException(
            "Harbor.slnx not found above " + AppContext.BaseDirectory
            + " — this guard reads the workflow and the recording inputs and cannot run from a "
            + "published test host. Returning quietly here would be worse than throwing: it would "
            + "report 'every recording input is covered' without having read either.");
    }
}
