// TypeFilterRegistrationTests.cs — the guard for issue #478.
//
// WHY THIS FILE EXISTS
// --------------------
// `TypeFilterMiddleware` had a two-state constructor:
//
//     new TypeFilterMiddleware(logger)               -> _allowAll = true
//     new TypeFilterMiddleware(logger, typeof(Foo))  -> a real filter
//
// The empty form filtered NOTHING: `ProcessAsync` returned `true` for every event
// on every path. The CLI registered exactly that form — `HostBuilder.CliOptions`
// built the filter with no types — so the only middleware on the production event
// bus was a guaranteed no-op, while its doc-comment advertised
// "configuration-driven filtering" that no config key ever fed. There was not even
// a way to fill the list in later: the constructor is the only place `allowedTypes`
// is read, the field is `readonly`, and there is no mutator.
//
// It was not even free, which is what made the no-op worth closing rather than
// documenting. `TypeFilterMiddleware` declares `EventBusSinkKind.Mandatory`, and
// `InMemoryEventBus` reads that verdict ONCE in its constructor:
// `_hasMandatorySink = true` forces `_fastPathEligible = false`. So the CLI paid
// the mandatory-sink cost on every publish — the full slow path, queue-age
// envelope included, ~112 B/op per docs/BENCHMARKS.md 5.4 — and got none of the
// filtering benefit. The one sink that could justify itself was the one sink that
// did nothing, and it was the reason the CLI bus could not take the fast path.
//
// THE RULE
// --------
// Every construction of `TypeFilterMiddleware` in PRODUCT code (src/, apps/) must
// pass at least one allowed type. The constructor itself now throws
// `ArgumentException` on an empty allowlist, so this guard is the build-time half
// of the same contract: it names the offending FILE:LINE instead of leaving a
// reviewer to notice at runtime that a mandatory sink admits everything.
//
// WHY A SOURCE RULE
// -----------------
// `BannedSymbols.txt` cannot express this: the type name has to stay perfectly
// legal (the class works, and is exercised by tests and the benchmark), so what
// varies is a CALL SITE's argument list, not a symbol's existence. Same shape —
// and same reason — as `DefaultModelSingleSourceTests` (#599) and
// `MaybeAbsenceTests`.
//
// NON-VACUITY
// -----------
// A source scan that matches nothing is indistinguishable from a source scan that
// is broken, and a broken guard is worse than no guard because it is believed. The
// zero-site case is exactly the risk here, so it is closed from both sides: the
// discovery step must find a real file set that CONTAINS the middleware's own
// source, and the SAME matcher must flag a planted no-type construction, stay
// silent on a compliant one, and stay silent on comment and string prose. If the
// walk, the paren-matching, the comment mask or the string mask ever degrades,
// these go RED instead of quietly passing.
//
// KNOWN LIMITATION — stated, not hidden
// ------------------------------------
// This is a lexical scan, not a C# parser. It reads the source, blanks comments
// and string/char literal content (preserving offsets), then finds
// `new TypeFilterMiddleware(` and counts the arguments between the parentheses at
// nesting depth zero. A construction smuggled through a macro or a reflection
// call would be missed; so would a call whose type arguments are generated by a
// helper that happens to pass them all. The limitation is bounded by construction:
// the constructor now throws on an empty allowlist, so a missed call site fails at
// composition time regardless of what the scan saw. The guard exists to make the
// mistake cheap to find, not to be the only thing standing between the two.

using System.Text.RegularExpressions;

namespace Harbor.Architecture.Tests;

/// <summary>
///     Issue #478: a <c>TypeFilterMiddleware</c> built with no allowed type is a
///     filter that filters nothing while still declaring
///     <c>EventBusSinkKind.Mandatory</c>. Every product-code construction must
///     carry at least one type.
/// </summary>
public sealed class TypeFilterRegistrationTests
{
    /// <summary>
    ///     Product trees scanned for a typeless construction. <c>tests/</c> is
    ///     deliberately excluded: the test that pins the constructor's
    ///     <see cref="ArgumentException" /> has to write exactly the call this rule
    ///     forbids, and a guard that cannot be tested is a guard nobody tests.
    /// </summary>
    private static readonly string[] ProductTrees = ["src", "apps"];

    /// <summary>
    ///     The middleware's own source, named rather than globbed. Asserted to be
    ///     inside the scanned set so the rule cannot go blind by the type moving
    ///     out of <c>src/</c>.
    /// </summary>
    private const string TypeFilterSourceRelativePath = "src/Harbor.Registries/Events/TypeFilterMiddleware.cs";

    /// <summary>
    ///     A construction site: which file, which line, and the offending text. The
    ///     tuple every failure message is built from.
    /// </summary>
    private sealed record ConstructionSite(string RelativePath, int Line, string Text);

    /// <summary>
    ///     The construction expression itself. <c>\s*</c> around the paren so a
    ///     line-broken <c>new TypeFilterMiddleware\n(</c> is still found.
    /// </summary>
    private static readonly Regex Construction = new(
        @"new\s+TypeFilterMiddleware\s*\(",
        RegexOptions.Compiled);

    /// <summary>
    ///     No product code constructs a typeless filter. Zero hits is the DESIRED
    ///     state, not an accident of the scan — see the non-vacuity tests below for
    ///     why that distinction is enforced rather than assumed.
    /// </summary>
    [Test]
    public async Task EveryProductConstruction_PassesAtLeastOneAllowedType()
    {
        string root = RequireRepoRoot();
        IReadOnlyList<string> files = EnumerateProductCsFiles(root);

        List<ConstructionSite> typeless = [.. files.SelectMany(f => ReadTypelessConstructions(root, f))];

        await Assert.That(typeless.Count).IsEqualTo(0)
            .Because(
                "TypeFilterMiddleware built with no allowed type filters NOTHING (ProcessAsync returns true "
                + "for every event) while still declaring EventBusSinkKind.Mandatory, which keeps "
                + "InMemoryEventBus off its fast path — the most expensive kind of no-op. Offenders: "
                + Describe(typeless)
                + ". Pass the event types the sink is meant to admit, or delete the construction and "
                + "register no filter at all. See issue #478.");
    }

    /// <summary>
    ///     Non-vacuity, part 1: the walk must find a real, non-trivial file set that
    ///     contains the middleware's own source. A scan rooted at a typo finds zero
    ///     files and then passes everything, which for THIS rule is indistinguishable
    ///     from the repo having solved the bug.
    /// </summary>
    [Test]
    public async Task Discovery_FindsARealFileSet_IncludingTheMiddlewareItself()
    {
        IReadOnlyList<string> files = EnumerateProductCsFiles(RequireRepoRoot());

        await Assert.That(files.Count).IsGreaterThan(200)
            .Because("src/ + apps/ hold an order of magnitude more than 200 C# files; a smaller count means the glob broke.");
        await Assert.That(files.Contains(TypeFilterSourceRelativePath)).IsTrue()
            .Because(TypeFilterSourceRelativePath + " must be inside the scanned set, or the guard polices nothing.");
    }

    /// <summary>
    ///     Non-vacuity, parts 2–4: the SAME matcher must flag the typeless
    ///     construction (including the one split across two lines, which is how a
    ///     zero-argument <c>params</c> call actually gets written), stay silent on a
    ///     construction that carries a type, and count arguments at the right
    ///     nesting depth. This is what separates "the guard is green" from "the
    ///     guard is looking at nothing".
    /// </summary>
    [Test]
    public async Task Matcher_FlagsTypelessConstruction_AndIgnoresTheCompliantOne()
    {
        const string Logger = "NullLogger<TypeFilterMiddleware>.Instance";

        string[] typeless =
        [
            "var mw = new TypeFilterMiddleware(" + Logger + ");",

            // Line-broken: the historical #478 call site in HostBuilder.cs was
            // itself split across lines, so a matcher that only reads one line at
            // a time would have missed the very defect this guard exists for.
            "var mw = new TypeFilterMiddleware(" + Logger + ",",
            "                           typeof(TurnStartEvent));"
        ];

        string[] compliant =
        [
            "var mw = new TypeFilterMiddleware(" + Logger + ", typeof(TurnStartEvent));",
            "var mw = new TypeFilterMiddleware(" + Logger + ", typeof(A), typeof(B));",

            // Nested commas belong to the argument, not to the top-level list.
            "var mw = new TypeFilterMiddleware(factory.Create(typeof(A), typeof(B)), typeof(C));"
        ];

        await Assert.That(FindTypelessConstructions("planted.cs", string.Join("\n", typeless)).Count).IsEqualTo(1)
            .Because("a filter constructed with only a logger IS the #478 defect and must be flagged; the line-broken pair is compliant");
        await Assert.That(FindTypelessConstructions("planted.cs", string.Join("\n", compliant)).Count).IsEqualTo(0)
            .Because("a filter that carries at least one type is compliant — flagging it would make the guard noise");
    }

    /// <summary>
    ///     Non-vacuity, parts 5–7: prose is prose. The same three characters appear
    ///     in a line comment, in a block comment and inside a string literal in this
    ///     very repository (the middleware's own doc-comment used to describe the
    ///     typeless construction at length), and none of those is a call site.
    /// </summary>
    [Test]
    public async Task Matcher_IgnoresCommentAndStringProse()
    {
        const string Logger = "NullLogger<TypeFilterMiddleware>.Instance";

        await Assert.That(FindTypelessConstructions("planted.cs", "// new TypeFilterMiddleware(" + Logger + ") was here").Count)
            .IsEqualTo(0)
            .Because("a line comment naming the defect is prose, not a call site");
        await Assert.That(FindTypelessConstructions("planted.cs", "/* new TypeFilterMiddleware(" + Logger + ") */").Count)
            .IsEqualTo(0)
            .Because("a block comment naming the defect is prose, not a call site");
        await Assert.That(FindTypelessConstructions("planted.cs", "var s = \"new TypeFilterMiddleware(" + Logger + ")\";").Count)
            .IsEqualTo(0)
            .Because("the same text inside a string literal is data, not a call site");
    }

    /// <summary>
    ///     Finds every construction in one file whose argument list is just the
    ///     logger — that is, a filter with no allowed type.
    /// </summary>
    private static List<ConstructionSite> FindTypelessConstructions(string relativePath, string text)
    {
        // Comments and literal CONTENT are blanked (offsets preserved) so that
        // neither prose nor a string can present itself as a call site, while
        // real code — including the parens inside its arguments — survives intact.
        string masked = MaskCommentsAndLiterals(text);

        var hits = new List<ConstructionSite>();
        foreach (Match call in Construction.Matches(masked))
        {
            int open = call.Index + call.Length - 1;
            int close = FindMatchingParen(masked, open);
            if (close < 0)
            {
                // Unbalanced parentheses: a broken file, not a defect this rule owns.
                continue;
            }

            if (CountArguments(masked, open + 1, close) >= 2)
            {
                // Logger plus at least one allowed type — a real filter.
                continue;
            }

            hits.Add(new ConstructionSite(relativePath, CountLines(masked, call.Index), LineAt(text, call.Index)));
        }

        return hits;
    }

    /// <summary>
    ///     Blanks comment bodies and the contents of string/char literals, leaving
    ///     every other character — and every offset — exactly as it was.
    /// </summary>
    private static string MaskCommentsAndLiterals(string text)
    {
        var buffer = text.ToCharArray();

        int i = 0;
        while (i < text.Length)
        {
            i = MaskOneToken(text, buffer, i);
        }

        return new string(buffer);
    }

    /// <summary>
    ///     Consumes the token starting at <paramref name="i" /> when it is a
    ///     comment or a literal, and returns where the next token begins — or
    ///     <paramref name="i" /> + 1 when the character is ordinary code.
    /// </summary>
    private static int MaskOneToken(string text, char[] buffer, int i)
    {
        if (At(text, i, "//"))
        {
            int end = text.IndexOf('\n', i);
            if (end < 0)
            {
                end = text.Length;
            }

            Blank(buffer, i, end);
            return end;
        }

        if (At(text, i, "/*"))
        {
            int close = text.IndexOf("*/", i + 2, StringComparison.Ordinal);
            int end = close < 0 ? text.Length : close + 2;
            Blank(buffer, i, end);
            return end;
        }

        if (At(text, i, "@\""))
        {
            return SkipVerbatimString(text, buffer, i + 1);
        }

        if (At(text, i, "\""))
        {
            return SkipQuoted(text, buffer, i, '"');
        }

        if (At(text, i, "'"))
        {
            return SkipQuoted(text, buffer, i, '\'');
        }

        return i + 1;
    }

    /// <summary>Whether <paramref name="text" /> carries <paramref name="token" /> at <paramref name="i" />.</summary>
    private static bool At(string text, int i, string token)
        => i + token.Length <= text.Length && string.CompareOrdinal(text, i, token, 0, token.Length) == 0;

    /// <summary>
    ///     Blanks a range in place, keeping newlines so reported line numbers stay
    ///     truthful for verbatim strings and block comments.
    /// </summary>
    private static void Blank(char[] buffer, int from, int to)
    {
        int end = Math.Min(to, buffer.Length);
        for (int k = Math.Max(from, 0); k < end; k++)
        {
            if (buffer[k] != '\n')
            {
                buffer[k] = ' ';
            }
        }
    }

    /// <summary>
    ///     Walks past a verbatim string starting at its opening quote. A doubled
    ///     quote is a literal quote, not the end of the string.
    /// </summary>
    private static int SkipVerbatimString(string text, char[] buffer, int openQuote)
    {
        int i = openQuote + 1;
        while (i < text.Length)
        {
            if (text[i] == '"')
            {
                if (i + 1 < text.Length && text[i + 1] == '"')
                {
                    Blank(buffer, i, i + 2);
                    i += 2;
                    continue;
                }

                return i + 1;
            }

            if (text[i] != '\n')
            {
                buffer[i] = ' ';
            }

            i++;
        }

        return i;
    }

    /// <summary>
    ///     Walks past a regular (possibly interpolated) string or a char literal
    ///     starting at its opening quote, blanking the content. An unterminated
    ///     literal ends at the newline rather than running away through the file.
    /// </summary>
    private static int SkipQuoted(string text, char[] buffer, int openQuote, char terminator)
    {
        int i = openQuote + 1;
        while (i < text.Length)
        {
            char c = text[i];

            if (c == '\\' && i + 1 < text.Length)
            {
                if (c != '\n')
                {
                    buffer[i] = ' ';
                }

                if (text[i + 1] != '\n')
                {
                    buffer[i + 1] = ' ';
                }

                i += 2;
                continue;
            }

            if (c == terminator)
            {
                return i + 1;
            }

            if (c == '\n')
            {
                return i;
            }

            buffer[i] = ' ';
            i++;
        }

        return i;
    }

    /// <summary>Index of the parenthesis closing the one at <paramref name="openIndex" />, or -1.</summary>
    private static int FindMatchingParen(string masked, int openIndex)
    {
        int depth = 0;
        for (int i = openIndex; i < masked.Length; i++)
        {
            char c = masked[i];
            if (c == '(')
            {
                depth++;
            }
            else if (c == ')')
            {
                depth--;
                if (depth == 0)
                {
                    return i;
                }
            }
        }

        return -1;
    }

    /// <summary>
    ///     Arguments between two parens, counting only commas at nesting depth zero
    ///     and reporting 0 for an all-whitespace range.
    /// </summary>
    private static int CountArguments(string masked, int from, int to)
    {
        int depth = 0;
        int commas = 0;
        bool anyContent = false;

        for (int i = from; i < to && i < masked.Length; i++)
        {
            char c = masked[i];
            if (c is '(' or '[' or '{')
            {
                depth++;
            }
            else if (c is ')' or ']' or '}')
            {
                depth--;
            }
            else if (c == ',' && depth == 0)
            {
                commas++;
            }

            if (!char.IsWhiteSpace(c))
            {
                anyContent = true;
            }
        }

        return anyContent ? commas + 1 : 0;
    }

    private static int CountLines(string text, int index)
    {
        int line = 1;
        for (int i = 0; i < index && i < text.Length; i++)
        {
            if (text[i] == '\n')
            {
                line++;
            }
        }

        return line;
    }

    private static string LineAt(string text, int index)
    {
        int start = text.LastIndexOf('\n', Math.Min(index, text.Length - 1));
        start = start < 0 ? 0 : start + 1;
        int end = text.IndexOf('\n', index);
        if (end < 0)
        {
            end = text.Length;
        }

        return text[start..end].Trim();
    }

    private static string Describe(IReadOnlyList<ConstructionSite> sites)
        => sites.Count == 0 ? "(none)" : string.Join(", ", sites.Select(s => s.RelativePath + ":" + s.Line + " → " + s.Text));

    private static string RequireRepoRoot()
    {
        string? root = RepoPaths.RepoRoot;
        return root ?? throw new InvalidOperationException(
            "Harbor.slnx not found above " + AppContext.BaseDirectory
            + " — this guard walks the repository and cannot run from a published test host.");
    }

    private static IReadOnlyList<string> EnumerateProductCsFiles(string root)
    {
        var files = new List<string>();
        foreach (string tree in ProductTrees)
        {
            string dir = Path.Combine(root, tree);
            if (!Directory.Exists(dir))
            {
                continue;
            }

            // Build output only. No worktree filter here: the walk starts at
            // <root>/src and <root>/apps, so a nested checkout under
            // <root>/.worktrees is out of reach anyway — and matching on it
            // would be actively wrong, because a checkout that ITSELF lives in
            // .worktrees would filter itself out and the scan would find nothing.
            files.AddRange(Directory.GetFiles(dir, "*.cs", SearchOption.AllDirectories)
                .Where(p => !IsBuildOutput(p))
                .Select(p => Path.GetRelativePath(root, p).Replace('\\', '/')));
        }

        files.Sort(StringComparer.Ordinal);
        return files;
    }

    private static bool IsBuildOutput(string path)
    {
        string normalized = path.Replace('\\', '/');
        return normalized.Contains("/obj/", StringComparison.Ordinal)
               || normalized.Contains("/bin/", StringComparison.Ordinal);
    }

    private static List<ConstructionSite> ReadTypelessConstructions(string root, string relativePath)
    {
        string text;
        try
        {
            text = File.ReadAllText(Path.Combine(root, relativePath));
        }
        catch (IOException)
        {
            return [];
        }
        catch (UnauthorizedAccessException)
        {
            return [];
        }

        return FindTypelessConstructions(relativePath, text);
    }
}
