<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Harbor.Terminal.Pty/Harbor.Terminal.Pty.csproj"/>
    <PackageReference Include="CSharpFunctionalExtensions"/>
  </ItemGroup>

</Project>
