// DesignSystemDocGen — builds the public theme API docs for Harbor.DesignSystem.
//
// Inputs:
//   - the compiler-generated XML doc file of Harbor.DesignSystem (XML comments
//     in DesignTokens.cs / Typography.cs / TerminalColorPalette.cs / ... are the
//     single source of truth for the reference),
//   - docs/schemas/harbor-theme.schema.json (theme slot descriptions),
//   - HarborTheme built-ins (example theme emission via ThemeJson.Write).
//
// Docs rot fails the build: every listed token must exist in the doc XML.
using System.Text;
using System.Text.Json;
using System.Xml.Linq;
using Harbor.DesignSystem;

var repoRoot = FindRepoRoot();
string mode = args.Length > 0 ? args[0] : "all";
string docXml = args.Length > 1 ? args[1]
    : Path.Combine(repoRoot, "src", "Harbor.DesignSystem", "bin", "Release", "net10.0", "Harbor.DesignSystem.xml");

if (mode is "api" or "all")
{
    GenerateApiReference(docXml, Path.Combine(repoRoot, "docs", "DESIGN_SYSTEM_API.md"));
    Console.WriteLine($"api reference written: docs/DESIGN_SYSTEM_API.md");
}

if (mode is "examples" or "all")
{
    string outDir = Path.Combine(repoRoot, "docs", "themes");
    Directory.CreateDirectory(outDir);
    foreach (var theme in new[] { HarborTheme.HarborDark, HarborTheme.HarborLight, HarborTheme.HarborWarm })
    {
        string path = Path.Combine(outDir, theme.Name + ".json");
        File.WriteAllText(path, ThemeJson.Write(theme));
        Console.WriteLine($"example theme written: docs/themes/{theme.Name}.json");
    }
}

return 0;

void GenerateApiReference(string xmlPath, string outPath)
{
    if (!File.Exists(xmlPath))
    {
        Console.Error.WriteLine($"doc XML not found: {xmlPath} — build Harbor.DesignSystem (Release) first");
        Environment.Exit(1);
    }

    var doc = XDocument.Load(xmlPath);
    var members = doc.Descendants("member")
        .ToDictionary(m => (string?)m.Attribute("name") ?? "", m => m);

    var md = new StringBuilder();
    md.AppendLine("# Harbor.DesignSystem — API Reference");
    md.AppendLine();
    md.AppendLine("> Generated by `tools/DesignSystemDocGen` from the XML doc comments and");
    md.AppendLine("> `docs/schemas/harbor-theme.schema.json`. Do not edit by hand — run");
    md.AppendLine("> `dotnet run --project tools/DesignSystemDocGen -c Release -- api` after");
    md.AppendLine("> changing tokens or schema.");
    md.AppendLine();

    AppendDesignTokens(md, members);
    AppendTypography(md, members);
    AppendThemeSlots(md);
    AppendRuntimeApi(md, members);

    Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
    File.WriteAllText(outPath, md.ToString());
}

void AppendDesignTokens(StringBuilder md, Dictionary<string, XElement> members)
{
    md.AppendLine("## Design tokens");
    md.AppendLine();
    md.AppendLine("Spacing, corner-radius, and font-size scale — matched to the 4/8/12/16/24/32/48/64 px");
    md.AppendLine("system used by every Harbor desktop app.");
    md.AppendLine();

    var fields = typeof(DesignTokens).GetFields()
        .Where(f => f.IsPublic && f.IsStatic)
        .Select(f => (Name: f.Name, Value: f.GetRawConstantValue()!.ToString() ?? "",
                      Summary: GetSummary(members, "F:Harbor.DesignSystem.DesignTokens." + f.Name)))
        .Where(f => f.Summary is not null)
        .ToList();

    int missing = typeof(DesignTokens).GetFields().Length - fields.Count;
    if (missing > 0)
    {
        Console.Error.WriteLine($"{missing} DesignTokens fields lack XML summaries — document them");
        Environment.Exit(1);
    }

    AppendGroup(md, "Spacing", fields, n => n.StartsWith("Space", StringComparison.Ordinal));
    AppendGroup(md, "Corner radius", fields, n => n.StartsWith("Radius", StringComparison.Ordinal));
    AppendGroup(md, "Font sizes", fields, n => n.StartsWith("FontSize", StringComparison.Ordinal));
    AppendGroup(md, "Font weights", fields, n => n.StartsWith("FontWeight", StringComparison.Ordinal));
}

void AppendGroup(StringBuilder md, string title, List<(string Name, string Value, string? Summary)> fields,
    Func<string, bool> match)
{
    md.AppendLine($"### {title}");
    md.AppendLine();
    md.AppendLine("| Token | Value | Description |");
    md.AppendLine("|---|---|---|");
    foreach (var f in fields.Where(f => match(f.Name)))
    {
        md.AppendLine($"| `{f.Name}` | {f.Value} | {f.Summary} |");
    }

    md.AppendLine();
}

void AppendTypography(StringBuilder md, Dictionary<string, XElement> members)
{
    md.AppendLine("## Typography");
    md.AppendLine();
    md.AppendLine("| Token | Value | Description |");
    md.AppendLine("|---|---|---|");
    foreach (var f in typeof(Typography).GetFields().Where(f => f.IsPublic && f.IsStatic))
    {
        string value = (string)f.GetRawConstantValue()!;
        md.AppendLine($"| `{f.Name}` | `{value}` | {GetSummary(members, "F:Harbor.DesignSystem.Typography." + f.Name)} |");
    }

    md.AppendLine();
}

void AppendThemeSlots(StringBuilder md)
{
    string schemaPath = Path.Combine(FindRepoRoot(), "docs", "schemas", "harbor-theme.schema.json");
    using var schema = JsonDocument.Parse(File.ReadAllText(schemaPath));
    var props = schema.RootElement.GetProperty("properties");

    md.AppendLine("## Theme slots (HDS v1)");
    md.AppendLine();
    md.AppendLine("Every Harbor theme — built-in or marketplace JSON — resolves these 14 color slots");
    md.AppendLine("plus `name`. In theme JSON every slot is optional: omitted slots merge over the");
    md.AppendLine("active theme. See the [theme guide](DESIGN_SYSTEM.md) and the");
    md.AppendLine("[JSON schema](schemas/harbor-theme.schema.json).");
    md.AppendLine();
    md.AppendLine("| Slot | Description | Dark reference |");
    md.AppendLine("|---|---|---|");
    foreach (var slot in props.EnumerateObject())
    {
        string description = slot.Value.GetProperty("description").GetString() ?? "";
        string reference = ExtractReference(description);
        description = description.Split(" (dark reference")[0].TrimEnd('.');
        md.AppendLine($"| `{slot.Name}` | {description} | {reference} |");
    }

    md.AppendLine();
}

string ExtractReference(string description)
{
    int open = description.IndexOf("(dark reference:", StringComparison.Ordinal);
    if (open < 0)
    {
        return "—";
    }

    int close = description.IndexOf(')', open);
    return description.Substring(open + "(dark reference: ".Length, close - open - "(dark reference: ".Length);
}

void AppendRuntimeApi(StringBuilder md, Dictionary<string, XElement> members)
{
    var asm = typeof(HarborTheme).Assembly;

    var orderedTypes = asm.GetExportedTypes()
        .Where(t => t.Namespace is "Harbor.DesignSystem" or "Harbor.Ui.Framework.Projection"
            or "Harbor.Ui.Framework.Rendering" or "Harbor.Ui.Framework.Rendering.Widgets")
        .Select(t => (Type: t, Key: "T:" + t.FullName))
        .Select(t => (t.Type, t.Key, Summary: GetSummary(members, t.Key)))
        .OrderBy(t => t.Type.Namespace)
        .ThenBy(t => t.Type.Name)
        .ToList();

    md.AppendLine("## Runtime API");
    md.AppendLine();
    md.AppendLine("Public surface of the `Harbor.DesignSystem` package assembly. The color/cell");
    md.AppendLine("primitives keep their historical `Harbor.Ui.Framework.*` namespaces for");
    md.AppendLine("compatibility; they physically live in this assembly.");
    md.AppendLine();
    md.AppendLine("| Type | Namespace | Summary |");
    md.AppendLine("|---|---|---|");
    foreach (var t in orderedTypes)
    {
        md.AppendLine($"| `{t.Type.Name}` | `{t.Type.Namespace}` | {t.Summary ?? "—"} |");
    }

    md.AppendLine();
}

string? GetSummary(Dictionary<string, XElement> members, string key)
{
    if (!members.TryGetValue(key, out var member))
    {
        return null;
    }

    var summary = member.Element("summary");
    if (summary is null)
    {
        return null;
    }

    // Flatten: inline <see cref="X"/> as the target's last name segment (method
    // signature suffix stripped), keep <see href> URLs, inline <paramref>, then
    // collapse all whitespace (markdown table cells).
    foreach (var see in summary.Descendants("see").ToList())
    {
        string href = (string?)see.Attribute("href") ?? "";
        string cref = (string?)see.Attribute("cref") ?? "";
        string replacement = href switch
        {
            not "" => href,
            // strip the method parameter list BEFORE segmenting — params contain dots.
            _ => cref.Split('(')[0]
                    .Split('.', ':', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) is { Length: > 0 } parts
                ? parts[^1]
                : cref,
        };
        see.ReplaceWith(new XText(replacement));
    }

    foreach (var paramref in summary.Descendants("paramref").ToList())
    {
        paramref.ReplaceWith(new XText((string?)paramref.Attribute("name") ?? ""));
    }

    return string.Join(' ', summary.Value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
}

string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Harbor.slnx")))
    {
        dir = dir.Parent!;
    }

    return dir?.FullName ?? throw new InvalidOperationException("repo root with Harbor.slnx not found");
}
