using System.Diagnostics;
using System.Text;

namespace Harbor.Application.Sessions;

/// <summary>
///     Declared check (epic #42, slice S4, #378): one command the operator
///     put in the run — via CLI flags or a checked-in checks file — to be
///     executed against the isolated copy. Checks are never generated by the
///     agent: the agent cannot add a check that makes its own work look
///     verified. The S9 driver (#397) parses operator input into
///     <see cref="CheckSpec" /> values; this runner only executes what it is
///     given.
/// </summary>
/// <param name="Name">Stable check name, recorded verbatim in checks.json.</param>
/// <param name="FileName">Binary to execute (no shell lookup) unless <see cref="Shell" /> is set.</param>
/// <param name="Args">Argument list, passed positionally (never a shell string).</param>
/// <param name="TimeoutSeconds">Wall-clock budget; the whole process tree is killed past it.</param>
/// <param name="OutputCapBytes">Per-stream capture cap; over-cap output is truncated with a marker.</param>
/// <param name="Shell">Opt-in shell execution (<c>/bin/sh -c</c>); flagged <c>viaShell</c> in checks.json.</param>
public sealed record CheckSpec(
    string Name,
    string FileName,
    IReadOnlyList<string> Args,
    int TimeoutSeconds = 600,
    int OutputCapBytes = 64 * 1024,
    bool Shell = false);

/// <summary>
///     Recorded outcome of one check. <c>Passed</c> is exit 0 only:
///     spawn failure and timeout are distinct outcomes, never passes.
/// </summary>
public enum CheckOutcome
{
    /// <summary>Exit code 0 (a truncated-but-0 check is still <c>Passed</c>, with the marker).</summary>
    Passed,

    /// <summary>Non-zero exit; the exit code and the tail of the output are recorded.</summary>
    Failed,

    /// <summary>The per-check timeout fired; the whole process tree was killed.</summary>
    TimedOut,

    /// <summary>The binary could not be started; nothing ran.</summary>
    SpawnFailed,

    /// <summary>Caller cancellation killed the in-flight process tree.</summary>
    Cancelled,

    /// <summary>Never started: an earlier check stopped the run, or cancellation arrived first.</summary>
    Skipped,
}

/// <summary>
///     Evidence for one executed check: exactly what was proven —
///     command X on revisions (base, head) in environment W.
/// </summary>
/// <param name="Name">Check name from the declaring <see cref="CheckSpec" />.</param>
/// <param name="CommandLine">Exact command line that ran (the <c>-c</c> payload when via shell).</param>
/// <param name="WorkingDirectory">Always the isolated worktree path, never the operator's root.</param>
/// <param name="ExitCode">Process exit code; null when nothing ran (spawn failure, cancel, skip).</param>
/// <param name="Outcome">Recorded outcome; only exit 0 is <see cref="CheckOutcome.Passed" />.</param>
/// <param name="Duration">Wall-clock time the check held (zero when nothing ran).</param>
/// <param name="BaseRevision">Frozen base revision the check is attributed to.</param>
/// <param name="HeadRevision">Frozen head revision the check is attributed to.</param>
/// <param name="EnvKeys">Effective environment key allowlist, sorted (the "env W" of the proof).</param>
/// <param name="Output">Captured stdout tail, capped at <c>OutputCapBytes</c>.</param>
/// <param name="ErrorOutput">Captured stderr tail, capped the same way.</param>
/// <param name="Truncated">True when either stream exceeded the cap — visible loss, never silent.</param>
/// <param name="ViaShell">True only for opt-in <c>Shell</c> specs.</param>
public sealed record CheckResult(
    string Name,
    string CommandLine,
    string WorkingDirectory,
    int? ExitCode,
    CheckOutcome Outcome,
    TimeSpan Duration,
    string BaseRevision,
    string HeadRevision,
    IReadOnlyList<string> EnvKeys,
    string Output,
    string ErrorOutput,
    bool Truncated,
    bool ViaShell);

/// <summary>
///     Evidence for a whole check run, persisted as
///     <c>runs/&lt;RunId&gt;/checks.json</c> for the S5 report (#379) to format.
///     Zero declared checks is legal: <see cref="HasChecks" /> is false and the
///     artifact carries <c>"checks": "none"</c>, which S5 must render as an
///     explicit "nothing was verified" statement.
/// </summary>
/// <param name="RunId">Run the checks belong to (matches the directory name).</param>
/// <param name="BaseRevision">Frozen base revision every check is attributed to.</param>
/// <param name="HeadRevision">Frozen head revision every check is attributed to.</param>
/// <param name="Checks">Per-check evidence, in declaration order.</param>
public sealed record CheckReport(
    string RunId,
    string BaseRevision,
    string HeadRevision,
    IReadOnlyList<CheckResult> Checks)
{
    /// <summary>False when the operator declared zero checks.</summary>
    public bool HasChecks => Checks.Count > 0;

    /// <summary>True only when at least one check ran and every check passed.</summary>
    public bool AllPassed
    {
        get
        {
            if (Checks.Count == 0)
                return false;
            for (int i = 0; i < Checks.Count; i++)
            {
                if (Checks[i].Outcome != CheckOutcome.Passed)
                    return false;
            }
            return true;
        }
    }
}

/// <summary>
///     Check runner (epic #42, stage S4): executes declared
///     <see cref="CheckSpec" /> values against the isolated worktree and
///     records exactly what was proven to <c>checks.json</c>.
/// </summary>
/// <remarks>
///     <para>
///         Fail-closed throughout: a revision mismatch against the materialized
///         workspace is a <c>Result.Failure</c>, not a warning; a missing
///         worktree, an unnamed check, or a non-positive timeout/cap is refused
///         before anything runs. The frozen (base, head) pair arrives from the
///         S3 change set (#377); until that slice lands, callers pass the pair
///         explicitly and every result still carries both revisions.
///     </para>
///     <para>
///         Process handling mirrors the <c>RunGitAsync</c> exited-task-vs-
///         infinite-delay shape: per-check timeout kills the whole process
///         tree, never <c>Task.WaitForExit</c> hangs. A check that daemonizes
///         past its own process group can still hold the capture pipes — that
///         escape is outside what <c>Kill(entireProcessTree: true)</c> reaches.
///     </para>
/// </remarks>
public static class CheckRunner
{
    private static readonly string[] AllowedEnvKeys = ["PATH", "HOME", "LANG", "TZ"];
    private const int DrainChunkBytes = 8192;

    /// <summary>
    ///     Run <paramref name="specs" /> in declaration order with
    ///     <c>WorkingDirectory</c> pinned to the isolated worktree, then write
    ///     <c>runs/&lt;RunId&gt;/checks.json</c>.
    /// </summary>
    /// <param name="workspace">Materialized isolated workspace (S2); its path is the only cwd.</param>
    /// <param name="baseRevision">Frozen base revision; must equal <c>workspace.BaseRevision</c>.</param>
    /// <param name="headRevision">Frozen head revision; recorded on every result.</param>
    /// <param name="specs">Operator-declared checks; empty is legal (records <c>checks: none</c>).</param>
    /// <param name="passthroughEnvKeys">
    ///     Contract-declared extra environment keys copied from the parent process.
    ///     Anything not listed here — including secrets planted in the parent env —
    ///     never reaches the child.
    /// </param>
    /// <param name="continueOnFailure">
    ///     Keep running after failure/timeout/spawn failure (the future <c>--continue</c> flag).
    ///     Cancellation always stops the run; the rest is recorded <c>Skipped</c>.
    /// </param>
    /// <param name="ct">
    ///     Caller cancellation: kills all in-flight check process trees, records
    ///     <c>Cancelled</c> (never <c>Passed</c>), leaves no orphan child process.
    /// </param>
    public static async Task<Result<CheckReport>> RunAsync(
        IsolatedWorkspace workspace,
        string baseRevision,
        string headRevision,
        IReadOnlyList<CheckSpec> specs,
        IReadOnlyList<string>? passthroughEnvKeys = null,
        bool continueOnFailure = false,
        CancellationToken ct = default)
    {
        if (workspace is null)
            return Result.Failure<CheckReport>("Isolated workspace must not be null.");
        if (specs is null)
            return Result.Failure<CheckReport>("Check specs must not be null (pass an empty list for zero checks).");
        if (string.IsNullOrWhiteSpace(baseRevision))
            return Result.Failure<CheckReport>("Base revision must not be empty.");
        if (string.IsNullOrWhiteSpace(headRevision))
            return Result.Failure<CheckReport>("Head revision must not be empty.");
        if (string.IsNullOrWhiteSpace(workspace.Path) || !Directory.Exists(workspace.Path))
            return Result.Failure<CheckReport>(
                $"Check run refused: worktree at '{workspace.Path}' does not exist — checks run against the isolated copy, never the operator's tree.");
        if (!workspace.BaseRevision.Equals(baseRevision, StringComparison.Ordinal))
            return Result.Failure<CheckReport>(
                $"Check run refused: frozen base {baseRevision} does not match worktree base {workspace.BaseRevision} — a mismatch is a failure, not a warning.");

        Result<string> runId = ValidateRunId(workspace.RunId.Value);
        if (runId.IsFailure)
            return runId.ConvertFailure<CheckReport>();

        for (int s = 0; s < specs.Count; s++)
        {
            Result<string> valid = ValidateSpec(specs[s], s);
            if (valid.IsFailure)
                return valid.ConvertFailure<CheckReport>();
        }

        IReadOnlyList<string> passthrough = passthroughEnvKeys ?? Array.Empty<string>();

        var results = new List<CheckResult>(specs.Count);
        bool stopped = false;
        for (int s = 0; s < specs.Count; s++)
        {
            if (stopped)
            {
                results.Add(SkippedResult(specs[s], workspace.Path, baseRevision, headRevision));
                continue;
            }
            if (ct.IsCancellationRequested)
            {
                results.Add(CancelledBeforeStart(specs[s], workspace.Path, baseRevision, headRevision, passthrough));
                stopped = true;
                continue;
            }
            CheckResult result = await RunOneAsync(
                specs[s], workspace.Path, baseRevision, headRevision, passthrough, ct).ConfigureAwait(false);
            results.Add(result);
            if (result.Outcome is CheckOutcome.Cancelled
                || (result.Outcome != CheckOutcome.Passed && !continueOnFailure))
                stopped = true;
        }

        var report = new CheckReport(runId.Value, baseRevision, headRevision, results);
        Result<string> written = WriteChecksJson(runId.Value, report);
        if (written.IsFailure)
            return written.ConvertFailure<CheckReport>();
        return Result.Success(report);
    }

    private static async Task<CheckResult> RunOneAsync(
        CheckSpec spec,
        string worktreePath,
        string baseRevision,
        string headRevision,
        IReadOnlyList<string> passthrough,
        CancellationToken ct)
    {
        var sw = Stopwatch.StartNew();
        string commandLine = FormatCommand(spec.FileName, spec.Args);
        string fileName = spec.Shell ? "/bin/sh" : spec.FileName;

        var psi = new ProcessStartInfo
        {
            FileName = fileName,
            WorkingDirectory = worktreePath,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        if (spec.Shell)
        {
            psi.ArgumentList.Add("-c");
            psi.ArgumentList.Add(commandLine);
        }
        else
        {
            for (int a = 0; a < spec.Args.Count; a++)
                psi.ArgumentList.Add(spec.Args[a]);
        }
        IReadOnlyList<string> envKeys = ApplyEnvironment(psi, passthrough);

        using var proc = new Process { StartInfo = psi, EnableRaisingEvents = true };
        var exited = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
        proc.Exited += (_, _) => exited.TrySetResult(true);
        bool started;
        try
        {
            started = proc.Start();
        }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception
            || ex is FileNotFoundException
            || ex is InvalidOperationException
            || ex is UnauthorizedAccessException)
        {
            sw.Stop();
            return SpawnFailedResult(spec, commandLine, worktreePath, baseRevision, headRevision, envKeys, sw.Elapsed, ex.Message);
        }
        if (!started)
        {
            sw.Stop();
            return SpawnFailedResult(spec, commandLine, worktreePath, baseRevision, headRevision, envKeys, sw.Elapsed, "process failed to start.");
        }

        Task<StreamCapture> stdoutTask = DrainAsync(proc.StandardOutput.BaseStream, spec.OutputCapBytes);
        Task<StreamCapture> stderrTask = DrainAsync(proc.StandardError.BaseStream, spec.OutputCapBytes);

        using var timeoutCts = new CancellationTokenSource(TimeSpan.FromSeconds(spec.TimeoutSeconds));
        try
        {
            Task ctTask = Task.Delay(Timeout.InfiniteTimeSpan, ct);
            Task timeoutTask = Task.Delay(Timeout.InfiniteTimeSpan, timeoutCts.Token);
            Task done = await Task.WhenAny(
                exited.Task, timeoutTask, ctTask).ConfigureAwait(false);
            if (!ReferenceEquals(done, exited.Task))
            {
                // Caller cancellation and the per-check timeout both land here:
                // the WhenAny above must observe ct, otherwise a cancel that
                // fires while the child still runs is ignored until the child
                // exits on its own (a 30s sleep cancelled at 300ms was recorded
                // Passed after the full 30s). ct wins the tie: the caller asked
                // to stop, so the record says Cancelled, never Passed.
                bool cancelled = ct.IsCancellationRequested;
                KillTree(proc);
                StreamCapture earlyOut = await stdoutTask.ConfigureAwait(false);
                StreamCapture earlyErr = await stderrTask.ConfigureAwait(false);
                sw.Stop();
                return new CheckResult(
                    spec.Name, commandLine, worktreePath, null,
                    cancelled ? CheckOutcome.Cancelled : CheckOutcome.TimedOut, sw.Elapsed,
                    baseRevision, headRevision, envKeys,
                    earlyOut.Text, earlyErr.Text,
                    earlyOut.Truncated || earlyErr.Truncated, spec.Shell);
            }

            await proc.WaitForExitAsync(ct).ConfigureAwait(false);
            StreamCapture stdoutCap = await stdoutTask.ConfigureAwait(false);
            StreamCapture stderrCap = await stderrTask.ConfigureAwait(false);
            sw.Stop();
            CheckOutcome outcome = proc.ExitCode == 0 ? CheckOutcome.Passed : CheckOutcome.Failed;
            return new CheckResult(
                spec.Name, commandLine, worktreePath, proc.ExitCode, outcome, sw.Elapsed,
                baseRevision, headRevision, envKeys,
                stdoutCap.Text, stderrCap.Text,
                stdoutCap.Truncated || stderrCap.Truncated, spec.Shell);
        }
        catch (OperationCanceledException)
        {
            KillTree(proc);
            StreamCapture cancelOut = await stdoutTask.ConfigureAwait(false);
            StreamCapture cancelErr = await stderrTask.ConfigureAwait(false);
            sw.Stop();
            return new CheckResult(
                spec.Name, commandLine, worktreePath, null, CheckOutcome.Cancelled, sw.Elapsed,
                baseRevision, headRevision, envKeys,
                cancelOut.Text, cancelErr.Text,
                cancelOut.Truncated || cancelErr.Truncated, spec.Shell);
        }
    }

    private static CheckResult SpawnFailedResult(
        CheckSpec spec, string commandLine, string worktreePath,
        string baseRevision, string headRevision, IReadOnlyList<string> envKeys,
        TimeSpan elapsed, string reason) =>
        new(spec.Name, commandLine, worktreePath, null, CheckOutcome.SpawnFailed, elapsed,
            baseRevision, headRevision, envKeys,
            $"Cannot start '{commandLine}': {reason}", string.Empty, false, spec.Shell);

    private static CheckResult SkippedResult(
        CheckSpec spec, string worktreePath, string baseRevision, string headRevision) =>
        new(spec.Name, FormatCommand(spec.FileName, spec.Args), worktreePath,
            null, CheckOutcome.Skipped, TimeSpan.Zero,
            baseRevision, headRevision, Array.Empty<string>(),
            string.Empty, string.Empty, false, spec.Shell);

    private static CheckResult CancelledBeforeStart(
        CheckSpec spec, string worktreePath, string baseRevision, string headRevision,
        IReadOnlyList<string> passthrough)
    {
        // Cancelled before launch: no process existed, so the effective keys are
        // computed, not observed — the shape matches a check that never ran.
        var keys = new List<string>(AllowedEnvKeys.Length + passthrough.Count);
        for (int k = 0; k < AllowedEnvKeys.Length; k++)
        {
            if (Environment.GetEnvironmentVariable(AllowedEnvKeys[k]) is not null)
                keys.Add(AllowedEnvKeys[k]);
        }
        for (int k = 0; k < passthrough.Count; k++)
        {
            string name = passthrough[k];
            if (!string.IsNullOrWhiteSpace(name)
                && !keys.Contains(name)
                && Environment.GetEnvironmentVariable(name) is not null)
                keys.Add(name);
        }
        keys.Sort(StringComparer.Ordinal);
        return new CheckResult(
            spec.Name, FormatCommand(spec.FileName, spec.Args), worktreePath,
            null, CheckOutcome.Cancelled, TimeSpan.Zero,
            baseRevision, headRevision, keys,
            string.Empty, string.Empty, false, spec.Shell);
    }

    private static Result<string> ValidateSpec(CheckSpec? spec, int index)
    {
        if (spec is null)
            return Result.Failure<string>($"Check #{index}: spec must not be null.");
        if (string.IsNullOrWhiteSpace(spec.Name))
            return Result.Failure<string>($"Check #{index}: Name must not be empty — checks are declared by the operator, an unnamed check is rejected, never run.");
        if (string.IsNullOrWhiteSpace(spec.FileName))
            return Result.Failure<string>($"Check '{spec.Name}': FileName must not be empty.");
        if (spec.Args is null)
            return Result.Failure<string>($"Check '{spec.Name}': Args must not be null (pass an empty list for no arguments).");
        for (int a = 0; a < spec.Args.Count; a++)
        {
            if (spec.Args[a] is null)
                return Result.Failure<string>($"Check '{spec.Name}': arg #{a} must not be null.");
        }
        if (spec.TimeoutSeconds <= 0)
            return Result.Failure<string>($"Check '{spec.Name}': TimeoutSeconds must be positive (got {spec.TimeoutSeconds}).");
        if (spec.OutputCapBytes <= 0)
            return Result.Failure<string>($"Check '{spec.Name}': OutputCapBytes must be positive (got {spec.OutputCapBytes}).");
        return Result.Success(spec.Name);
    }

    private static Result<string> ValidateRunId(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return Result.Failure<string>("Run ID cannot be empty.");
        if (value != Path.GetFileName(value) || value is "." or "..")
            return Result.Failure<string>($"Invalid run id '{value}': path separators are not allowed.");
        return Result.Success(value);
    }

    private static IReadOnlyList<string> ApplyEnvironment(ProcessStartInfo psi, IReadOnlyList<string> passthrough)
    {
        // Explicit minimal allowlist (the "env W" of the proof): PATH, HOME,
        // LANG, TZ plus contract-declared passthrough. The block starts as a
        // copy of the parent environment and is cleared first, so a planted
        // secret in the parent process never reaches the child unless the
        // operator declared its key.
        psi.Environment.Clear();
        var keys = new List<string>(AllowedEnvKeys.Length + passthrough.Count);
        for (int k = 0; k < AllowedEnvKeys.Length; k++)
            AddEnvIfPresent(psi, keys, AllowedEnvKeys[k]);
        for (int k = 0; k < passthrough.Count; k++)
        {
            string name = passthrough[k];
            if (string.IsNullOrWhiteSpace(name) || keys.Contains(name))
                continue;
            AddEnvIfPresent(psi, keys, name);
        }
        keys.Sort(StringComparer.Ordinal);
        return keys;
    }

    private static void AddEnvIfPresent(ProcessStartInfo psi, List<string> keys, string name)
    {
        string? value = Environment.GetEnvironmentVariable(name);
        if (value is null)
            return;
        psi.Environment[name] = value;
        keys.Add(name);
    }

    private static string FormatCommand(string fileName, IReadOnlyList<string> args)
    {
        var sb = new StringBuilder(fileName);
        for (int k = 0; k < args.Count; k++)
        {
            sb.Append(' ');
            sb.Append(QuoteArg(args[k] ?? string.Empty));
        }
        return sb.ToString();
    }

    private static string QuoteArg(string arg)
    {
        if (arg.Length == 0)
            return "\"\"";
        bool needs = false;
        for (int k = 0; k < arg.Length; k++)
        {
            char c = arg[k];
            if (char.IsWhiteSpace(c) || c is '"' or '\'' or '\\')
            {
                needs = true;
                break;
            }
        }
        if (!needs)
            return arg;
        var sb = new StringBuilder(arg.Length + 2);
        sb.Append('"');
        for (int k = 0; k < arg.Length; k++)
        {
            if (arg[k] == '"')
                sb.Append('\\');
            sb.Append(arg[k]);
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static void KillTree(Process proc)
    {
        try
        {
            proc.Kill(entireProcessTree: true);
        }
        catch (Exception ex)
        {
            _ = ex;
        }
    }

    private sealed record StreamCapture(string Text, bool Truncated);

    /// <summary>
    ///     Drain <paramref name="stream" /> to end keeping the last
    ///     <paramref name="capBytes" /> bytes (sliding window, bounded memory
    ///     no matter how much the child emits). The cap is honest bytes; a
    ///     window cut inside a UTF-8 sequence drops the leading partial char
    ///     rather than decoding a replacement.
    /// </summary>
    private static async Task<StreamCapture> DrainAsync(Stream stream, int capBytes)
    {
        var window = new byte[capBytes];
        int start = 0;
        int count = 0;
        bool truncated = false;
        var chunk = new byte[DrainChunkBytes];
        while (true)
        {
            int n;
            try
            {
                n = await stream.ReadAsync(chunk, 0, chunk.Length).ConfigureAwait(false);
            }
            catch (Exception ex) when (ex is IOException || ex is ObjectDisposedException || ex is InvalidOperationException)
            {
                break;
            }
            if (n == 0)
                break;
            for (int k = 0; k < n; k++)
            {
                if (count < capBytes)
                {
                    window[(start + count) % capBytes] = chunk[k];
                    count++;
                }
                else
                {
                    window[start] = chunk[k];
                    start = (start + 1) % capBytes;
                    truncated = true;
                }
            }
        }
        var linear = new byte[count];
        for (int k = 0; k < count; k++)
            linear[k] = window[(start + k) % capBytes];
        int offset = 0;
        if (truncated)
        {
            while (offset < count && offset < 4 && (linear[offset] & 0xC0) == 0x80)
                offset++;
        }
        return new StreamCapture(Encoding.UTF8.GetString(linear, offset, count - offset), truncated);
    }

    internal static string GetHarborHome()
    {
        // Same five lines as WorkspaceMaterializer (and the same reason they
        // live here rather than behind a Hosting ProjectReference): Application
        // depends on Domain only. HARBOR_HOME or ~/.harbor.
        if (Environment.GetEnvironmentVariable("HARBOR_HOME") is { Length: > 0 } custom)
            return custom;
        return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".harbor");
    }

    internal static string RunsRoot() => Path.Combine(GetHarborHome(), "runs");

    internal static string RunDir(string runId) => Path.Combine(RunsRoot(), runId);

    /// <summary>
    ///     Write <c>runs/&lt;RunId&gt;/checks.json</c> atomically (temp + rename).
    ///     Zero checks serialize as <c>"checks": "none"</c> — S5 (#379) turns
    ///     that into an explicit "nothing was verified" statement. Overwrite is
    ///     allowed: re-verification replaces the artifact, history is S5's job.
    /// </summary>
    private static Result<string> WriteChecksJson(string runId, CheckReport report)
    {
        string runDir = RunDir(runId);
        try
        {
            Directory.CreateDirectory(runDir);
        }
        catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException)
        {
            return Result.Failure<string>($"Cannot create run directory '{runDir}': {ex.Message}");
        }
        string path = Path.Combine(runDir, "checks.json");

        byte[] bytes;
        try
        {
            using var ms = new MemoryStream();
            using (var writer = new Utf8JsonWriter(ms, new JsonWriterOptions { Indented = true }))
            {
                writer.WriteStartObject();
                writer.WriteNumber("version", 1);
                writer.WriteString("runId", report.RunId);
                writer.WriteString("baseRevision", report.BaseRevision);
                writer.WriteString("headRevision", report.HeadRevision);
                if (!report.HasChecks)
                {
                    writer.WriteString("checks", "none");
                }
                else
                {
                    writer.WriteStartArray("checks");
                    for (int i = 0; i < report.Checks.Count; i++)
                    {
                        CheckResult r = report.Checks[i];
                        writer.WriteStartObject();
                        writer.WriteString("name", r.Name);
                        writer.WriteString("commandLine", r.CommandLine);
                        writer.WriteString("workingDirectory", r.WorkingDirectory);
                        if (r.ExitCode is null)
                            writer.WriteNull("exitCode");
                        else
                            writer.WriteNumber("exitCode", r.ExitCode.Value);
                        writer.WriteString("outcome", r.Outcome.ToString());
                        writer.WriteNumber("durationMs", (long)r.Duration.TotalMilliseconds);
                        writer.WriteString("baseRevision", r.BaseRevision);
                        writer.WriteString("headRevision", r.HeadRevision);
                        writer.WriteStartArray("envKeys");
                        for (int k = 0; k < r.EnvKeys.Count; k++)
                            writer.WriteStringValue(r.EnvKeys[k]);
                        writer.WriteEndArray();
                        writer.WriteString("output", r.Output);
                        writer.WriteString("errorOutput", r.ErrorOutput);
                        writer.WriteBoolean("truncated", r.Truncated);
                        writer.WriteBoolean("viaShell", r.ViaShell);
                        writer.WriteEndObject();
                    }
                    writer.WriteEndArray();
                }
                writer.WriteEndObject();
            }
            bytes = ms.ToArray();
        }
        catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException)
        {
            return Result.Failure<string>($"Cannot serialize checks for run '{runId}': {ex.Message}");
        }

        string tmp = path + ".tmp";
        try
        {
            File.WriteAllBytes(tmp, bytes);
        }
        catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException || ex is DirectoryNotFoundException)
        {
            return Result.Failure<string>($"Cannot write checks for run '{runId}': {ex.Message}");
        }
        try
        {
            File.Move(tmp, path, overwrite: true);
        }
        catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException || ex is DirectoryNotFoundException)
        {
            DeleteQuiet(tmp);
            return Result.Failure<string>($"Cannot write checks for run '{runId}': {ex.Message}");
        }
        return Result.Success(path);
    }

    private static void DeleteQuiet(string path)
    {
        try
        {
            if (File.Exists(path))
                File.Delete(path);
        }
        catch (Exception ex) when (ex is IOException || ex is UnauthorizedAccessException)
        {
            _ = ex;
        }
    }
}
