// <auto-generated>
//     Configures ZLinq drop-in source generation for Harbor.Abstractions.
//     Emits extension methods (in the global namespace so they win overload
//     resolution against System.Linq) for Array, Span, Memory, List, and
//     IEnumerable<T>. Combined with the `<Using Remove="System.Linq" />`
//     directive in Harbor.Abstractions.csproj, every LINQ call site in this
//     assembly resolves to ZLinq's zero-allocation ValueEnumerable pipeline
//     without rewriting call sites.
// </auto-generated>
using ZLinq;

[assembly: ZLinqDropInAttribute("", DropInGenerateTypes.Everything)]
