using MessagePack;
namespace Harbor.Ipc.Protocol;
/// <summary>
///     Base type for all Harbor IPC requests. Carries a client-generated
///     <see cref="RequestId" /> so the client can match responses to requests.
/// </summary>
/// <remarks>
///     <para>
///         <b>Wire format:</b> MessagePack [Union] tagged union. The integer
///         tag is the request-kind discriminator; each concrete request
///         record is annotated with <c>[MessagePackObject]</c> and positional
///         <c>[Key(N)]</c> members.
///     </para>
///     <para>
///         <b>Inheritance &amp; key ordering:</b> MessagePack requires base
///         members to be keyed first, then derived members. The base
///         <see cref="HarborRequest" /> owns <c>[Key(0)] = RequestId</c>.
///         Concrete derived records therefore start their own keys at
///         <c>[Key(1)]</c> and MUST NOT redeclare <see cref="RequestId" />.
///     </para>
    /// <para>
    ///         <b>Domain objects</b> (Session, AgentMessage, ToolDescriptor,
    ///         ModelInfo, ProviderId, ToolResult) are carried inside the
    ///         concrete request/response payloads as
    ///         <see cref="OkResponse.Payload" />-style <c>byte[]</c> —
    ///         MessagePack-serialized via
    ///         <see cref="WireCodec.SerializeDomain{T}" /> (typed, no wire
    ///         type metadata; they are POCOs with public get/init properties
    ///         handled by the StandardResolver). This keeps the wire contract
    ///         small and decoupled from the domain layer's [MemoryPackable]
    ///         attributes.
    ///     </para>
/// </remarks>
[MessagePackObject]
[Union(0, typeof(StartAgentRequest))]
[Union(1, typeof(AbortAgentRequest))]
[Union(2, typeof(SendPromptRequest))]
[Union(3, typeof(CreateSessionRequest))]
[Union(4, typeof(ListSessionsRequest))]
[Union(5, typeof(GetSessionRequest))]
[Union(6, typeof(DeleteSessionRequest))]
[Union(7, typeof(GetMessagesRequest))]
[Union(8, typeof(ListProvidersRequest))]
[Union(9, typeof(ListModelsRequest))]
[Union(10, typeof(ListToolsRequest))]
[Union(11, typeof(SubscribeToEventsRequest))]
[Union(12, typeof(ConnectRequest))]
[Union(13, typeof(DisconnectRequest))]
[Union(14, typeof(PskAuthRequest))]
public abstract record HarborRequest
{
    /// <summary>
    ///     Client-generated unique id for this request. The server copies it
    ///     into the matching <see cref="HarborResponse.RequestId" />.
    /// </summary>
    [Key(0)]
    public Guid RequestId { get; init; } = Guid.NewGuid();
}

// ── Agent ──────────────────────────────────────────────────────────────────

/// <summary>Bind the agent loop to a session.</summary>
[MessagePackObject]
public sealed record StartAgentRequest(
    [property: Key(1)] string SessionId,
    [property: Key(2)] string AgentName) : HarborRequest
{
    /// <summary>
    ///     Parameterless constructor for MessagePack source-generator
    ///     deserialization. The generator emits
    ///     <c>new StartAgentRequest() { SessionId = ..., AgentName = ... }</c>
    ///     which requires a parameterless ctor + init setters; positional
    ///     records only generate the parameterized ctor, so we add this
    ///     shim. The init setters (auto-generated by the record) override
    ///     the defaults passed here.
    /// </summary>
    public StartAgentRequest() : this(string.Empty, string.Empty) { }
}

/// <summary>Abort the in-flight run.</summary>
[MessagePackObject]
public sealed record AbortAgentRequest : HarborRequest;

/// <summary>Submit a user prompt and run the agent loop to completion.</summary>
[MessagePackObject]
public sealed record SendPromptRequest(
    [property: Key(1)] string Prompt) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public SendPromptRequest() : this(string.Empty) { }
}

// ── Sessions ───────────────────────────────────────────────────────────────

/// <summary>Create a new session.</summary>
[MessagePackObject]
public sealed record CreateSessionRequest(
    [property: Key(1)] string Directory,
    [property: Key(2)] string Agent,
    [property: Key(3)] string Provider,
    [property: Key(4)] string Model) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public CreateSessionRequest() : this(string.Empty, string.Empty, string.Empty, string.Empty) { }
}

/// <summary>List all sessions.</summary>
[MessagePackObject]
public sealed record ListSessionsRequest : HarborRequest;

/// <summary>Get a session by id.</summary>
[MessagePackObject]
public sealed record GetSessionRequest(
    [property: Key(1)] string SessionId) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public GetSessionRequest() : this(string.Empty) { }
}

/// <summary>Delete a session.</summary>
[MessagePackObject]
public sealed record DeleteSessionRequest(
    [property: Key(1)] string SessionId) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public DeleteSessionRequest() : this(string.Empty) { }
}

/// <summary>Get all messages for a session.</summary>
[MessagePackObject]
public sealed record GetMessagesRequest(
    [property: Key(1)] string SessionId) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public GetMessagesRequest() : this(string.Empty) { }
}

// ── Providers ──────────────────────────────────────────────────────────────

/// <summary>List registered provider ids.</summary>
[MessagePackObject]
public sealed record ListProvidersRequest : HarborRequest;

/// <summary>List models, optionally filtered by provider id.</summary>
[MessagePackObject]
public sealed record ListModelsRequest(
    [property: Key(1)] string? ProviderId) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public ListModelsRequest() : this((string?)null) { }
}

// ── Tools ──────────────────────────────────────────────────────────────────

/// <summary>List all registered tools.</summary>
[MessagePackObject]
public sealed record ListToolsRequest : HarborRequest;

// ── Streaming events ───────────────────────────────────────────────────────

/// <summary>
///     Open a server-pushed event stream. The server replies with an
///     <c>OkResponse</c> ack, then begins streaming <see cref="EventEnvelope" />
///     frames (out-of-band, not as a normal response).
/// </summary>
[MessagePackObject]
public sealed record SubscribeToEventsRequest : HarborRequest;

/// <summary>Connect handshake.</summary>
[MessagePackObject]
public sealed record ConnectRequest : HarborRequest;

/// <summary>Disconnect handshake.</summary>
[MessagePackObject]
public sealed record DisconnectRequest : HarborRequest;

/// <summary>
///     Pre-shared-key authentication frame. Required as the FIRST request
///     on any connection to a PSK-gated listener (TCP / tailscale); UDS
///     listeners may opt in via configuration. The server compares in
///     constant time and closes the connection on a failed attempt.
/// </summary>
[MessagePackObject]
public sealed record PskAuthRequest(
    [property: Key(1)] string Psk) : HarborRequest
{
    /// <summary>Parameterless ctor for MessagePack deserialization.</summary>
    public PskAuthRequest() : this(string.Empty) { }
}
